prompt --application/pages/page_00297
begin
--   Manifest
--     PAGE: 00297
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>297
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>'Monthly  Report'
,p_step_title=>'Monthly  Report'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_help_text=>'No help is available for this page.'
,p_last_updated_by=>'RILADM'
,p_last_upd_yyyymmddhh24miss=>'20161129124816'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(100956888210338392)
,p_plug_name=>'Monthly  Report'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>10
,p_plug_display_point=>'BODY_3'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT  s.rowid "rwid", b.DOCNUMBR,b.DOCTDATE,b.partycde customer_code, custname AS customer, custtype AS CATEGORY,',
'         custadr1 AS address, custphon phonenum, custmobl mobileno,',
'         custmail email_id, b.custcmpln AS custcmpln, b.remarkss AS remarkss,',
'         b.itemdesc vehicle, b.brand, b.registno, b.chasisno, b.delvrydt,',
'         b.endddate, b.startdte, b.nxtsrvdt, b.modlcode, b.modelnam',
'    FROM vwnmsvci b,nmservce s',
'   WHERE b.COMPCODE=s.COMPCODE',
'   and b.DOCTTYPE=s.DOCTTYPE',
'   and b.SUBTTYPE=s.SUBTTYPE',
'   and b.DOCNUMBR=s.DOCNUMBR',
'   and b.DOCTDATE=s.DOCTDATE',
'   and b.doctdate BETWEEN TRUNC (SYSDATE, ''MONTH'')',
'                                            AND LAST_DAY (TRUNC (SYSDATE,',
'                                                                 ''MONTH''',
'                                                                )',
'                                                         )',
'ORDER BY b.delvrydt DESC'))
,p_plug_source_type=>'NATIVE_IR'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(100957343142338392)
,p_name=>'Todays Report'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_fixed_header=>'NONE'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_pivot=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML'
,p_enable_mail_download=>'Y'
,p_allow_exclude_null_values=>'N'
,p_allow_hide_extra_columns=>'N'
,p_icon_view_columns_per_row=>1
,p_owner=>'RILADM'
,p_internal_uid=>63802476016657898
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100957393714338392)
,p_db_column_name=>'rwid'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Rwid'
,p_allow_sorting=>'N'
,p_allow_filtering=>'N'
,p_allow_highlighting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'OTHER'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'rwid'
,p_rpt_show_filter_lov=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100957778032338392)
,p_db_column_name=>'DOCNUMBR'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Service<br>No.'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'DOCNUMBR'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100958209090338392)
,p_db_column_name=>'DOCTDATE'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Service<br>Date'
,p_allow_pivot=>'N'
,p_column_type=>'DATE'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'DOCTDATE'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100958595210338392)
,p_db_column_name=>'CUSTOMER_CODE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Customer<br>Code'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'CUSTOMER_CODE'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100959017034338392)
,p_db_column_name=>'CUSTOMER'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Customer Name'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'CUSTOMER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100959419092338392)
,p_db_column_name=>'CATEGORY'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Customer<br>Category'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'CATEGORY'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100959787761338392)
,p_db_column_name=>'ADDRESS'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Customer<br>Address'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'ADDRESS'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100960218209338393)
,p_db_column_name=>'PHONENUM'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Phone<br>No.'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'PHONENUM'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100960567447338393)
,p_db_column_name=>'MOBILENO'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Mobile<br>No'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'MOBILENO'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100961037659338393)
,p_db_column_name=>'EMAIL_ID'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Email Id'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'EMAIL_ID'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100961466972338395)
,p_db_column_name=>'CUSTCMPLN'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Customer<br>Complain'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'CUSTCMPLN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100961815311338395)
,p_db_column_name=>'REMARKSS'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Remarkss'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'REMARKSS'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100962183861338395)
,p_db_column_name=>'VEHICLE'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Vehicle'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'VEHICLE'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100962656181338395)
,p_db_column_name=>'BRAND'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Brand'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'BRAND'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100963003830338395)
,p_db_column_name=>'REGISTNO'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Registration<br>No.'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'REGISTNO'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100963444555338395)
,p_db_column_name=>'CHASISNO'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Chasis<br>No.'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'CHASISNO'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100963836500338395)
,p_db_column_name=>'DELVRYDT'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Delivery<br>Date'
,p_allow_pivot=>'N'
,p_column_type=>'DATE'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'DELVRYDT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100964266537338397)
,p_db_column_name=>'ENDDDATE'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'End<br>Date'
,p_allow_pivot=>'N'
,p_column_type=>'DATE'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'ENDDDATE'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100964646222338397)
,p_db_column_name=>'STARTDTE'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Start<br>Date'
,p_allow_pivot=>'N'
,p_column_type=>'DATE'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'STARTDTE'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100965059861338397)
,p_db_column_name=>'NXTSRVDT'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Next<br>Service Date'
,p_allow_pivot=>'N'
,p_column_type=>'DATE'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'NXTSRVDT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100965411138338397)
,p_db_column_name=>'MODLCODE'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Model<br>Code'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'MODLCODE'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(100965794159338397)
,p_db_column_name=>'MODELNAM'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Model<br>Name'
,p_allow_pivot=>'N'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
,p_static_id=>'MODELNAM'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(100966176325338397)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'638114'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>15
,p_report_columns=>'DOCNUMBR:DOCTDATE:CUSTOMER_CODE:CUSTOMER:MOBILENO:EMAIL_ID:BRAND:DELVRYDT:VEHICLE:MODLCODE:MODELNAM:REGISTNO:CHASISNO:STARTDTE:ENDDDATE:NXTSRVDT:CUSTCMPLN:REMARKSS:'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(100966691205338398)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(100956888210338392)
,p_button_name=>'CANCEL'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Cancel'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:150:&SESSION.::&DEBUG.:::'
,p_grid_new_row=>'N'
,p_grid_new_column=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(100967133016338398)
,p_name=>'P297_SERVCENO'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(100956888210338392)
,p_source=>'Monthly Service Info'
,p_source_type=>'STATIC'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_tag_attributes=>'style="color:#6633FF;font-weight:bold;"'
,p_label_alignment=>'RIGHT'
,p_field_alignment=>'LEFT-CENTER'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(100967473373338398)
,p_name=>'Freeze Column'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(100968043224338398)
,p_event_id=>wwv_flow_api.id(100967473373338398)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'PLUGIN_COM.AF.PLUGIN.JQ.IRFREEZEHEADER'
,p_attribute_01=>'400'
,p_attribute_03=>'500'
,p_attribute_04=>'Y'
);
wwv_flow_api.component_end;
end;
/
