prompt --application/pages/page_00339
begin
--   Manifest
--     PAGE: 00339
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>339
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>'Opening Balance'
,p_page_mode=>'MODAL'
,p_step_title=>'Opening Balance'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'GADMIN'
,p_last_upd_yyyymmddhh24miss=>'20180211102549'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(206720383128725307)
,p_plug_name=>'Bank Details'
,p_region_template_options=>'#DEFAULT#:i-h100:t-Region--removeHeader:t-Region--hiddenOverflow:t-Form--leftLabels'
,p_region_attributes=>'style="background-color:&BACKGROUND_COLOR.;"'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>60
,p_plug_new_grid_row=>false
,p_plug_grid_column_span=>4
,p_plug_display_column=>9
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_plug_display_condition_type=>'NEVER'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(206724012827725343)
,p_plug_name=>'Button_region'
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--noBorder:t-Region--hiddenOverflow:t-Form--stretchInputs'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'REGION_POSITION_03'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(312741041025152169)
,p_plug_name=>'B'
,p_region_template_options=>'#DEFAULT#:i-h50:t-Region--removeHeader:t-Region--hiddenOverflow:t-Form--leftLabels'
,p_region_attributes=>'style="background-color:&BACKGROUND_COLOR.;"'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>30
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(327045736903243788)
,p_plug_name=>'A'
,p_region_template_options=>'#DEFAULT#:i-h100:t-Region--removeHeader:t-Region--hiddenOverflow:t-Form--leftLabels'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="background-color:&BACKGROUND_COLOR.;"'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>50
,p_plug_new_grid_row=>false
,p_plug_grid_column_span=>4
,p_plug_display_column=>5
,p_plug_item_display_point=>'BELOW'
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_plug_query_show_nulls_as=>' - '
,p_plug_display_condition_type=>'NEVER'
,p_pagination_display_position=>'BOTTOM_RIGHT'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(439572535643280021)
,p_plug_name=>'Opening Balance'
,p_region_name=>'t'
,p_region_template_options=>'#DEFAULT#:t-Region--hiddenOverflow'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>80
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select COMPCODE,',
'       DOCTTYPE,',
'       SUBTTYPE,',
'       DOCNUMBR,',
'       DOCTDATE,',
'       SERLNUMB,',
'       DOCDUEDT,',
'       ACCTCODE,',
'       COSTCODE,',
'       SUBLEDCD,',
'       TRANCODE,',
'       NARATION,',
'       DBCRCODE,',
'       CURRCODE,',
'       EXCGRATE,',
'       JVFCAMNT,',
'       JVLCAMNT,',
'       ORGAMTFC,',
'       ORGAMTLC,',
'       ADJAMTFC,',
'       ADJAMTLC,',
'       ORGBAKFC,',
'       ORGBAKLC,',
'       ADJBAKFC,',
'       ADJBAKLC,',
'       REFDOCNO,',
'       REFDOCDT,',
'       REFDOCTY,',
'       REFDCSTY,',
'       REFDCNUM,',
'       REFRDATE,',
'       INTDOCTY,',
'       INTDCSTY,',
'       INTDOCNO,',
'       INTDOCDT,',
'       CTRLMCRO,',
'       STATCODE,',
'       POSTDATE,',
'       POSTUSER,',
'       PURGFLAG,',
'       TRANSERL,',
'       ALLCFREZ,',
'       CHEQUENO,',
'       CHEQUEDT,',
'       BANKNAME,',
'       BANKBRCH,',
'       BANKCODE,',
'       EMPLACCT,',
'       OPRSTAMP,',
'       TIMSTAMP,',
'       REFSERNO,',
'       ITEMCODE,',
'       STOKQNTY,',
'       MSLCAMNT,',
'       REFRBANK,',
'       DEPOSTDT,',
'       REFBNKNM,',
'       MODIFYDT,',
'       YEARCODE,',
'       0 Debit_Amount,',
'       0 Credit_Amount,',
'       '''' customer',
'  from actrnopb',
'   where compcode = :compcode',
'  and docnumbr = :P339_DOCNUMBR',
'  and DOCTTYPE = :P339_TRNTYP --:P339_TRANTYPE',
'  and SUBTTYPE = :P339_SUBTYP --:P339_SUBTTYPE',
'--  and decode(rowid is null,ACCTCODE is null,ACCTCODE is not null)'))
,p_plug_source_type=>'NATIVE_IG'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(127553630322475030)
,p_name=>'APEX$ROW_ACTION'
,p_item_type=>'NATIVE_ROW_ACTION'
,p_display_sequence=>20
,p_enable_hide=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(127553795018475031)
,p_name=>'APEX$ROW_SELECTOR'
,p_item_type=>'NATIVE_ROW_SELECTOR'
,p_display_sequence=>10
,p_attribute_01=>'Y'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
,p_enable_hide=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(127554035699475034)
,p_name=>'YEARCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'YEARCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>650
,p_attribute_01=>'Y'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(128888689974813520)
,p_name=>'ROWID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ROWID'
,p_data_type=>'ROWID'
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>660
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(206721785401725321)
,p_name=>'DEBIT_AMOUNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DEBIT_AMOUNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>true
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Debit Amount'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>200
,p_value_alignment=>'CENTER'
,p_value_css_classes=>'debit'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(206721829275725322)
,p_name=>'CREDIT_AMOUNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CREDIT_AMOUNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>true
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Credit Amount'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>210
,p_value_alignment=>'CENTER'
,p_value_css_classes=>'credit'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(207955695345146238)
,p_name=>'CUSTOMER'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CUSTOMER'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_POPUP_LOV'
,p_heading=>'Customer'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>140
,p_value_alignment=>'LEFT'
,p_attribute_01=>'DIALOG'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_04=>'N'
,p_is_required=>false
,p_max_length=>0
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT prtyname CUSTNAME,partycde',
'    FROM sycompty',
'   WHERE compcode = :COMPCODE ',
'   AND NVL (partysts, 1) != 8',
'   ORDER BY 1'))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439574196783280048)
,p_name=>'COMPCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'COMPCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>40
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>':compcode'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439574881910280048)
,p_name=>'DOCTTYPE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCTTYPE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>50
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P339_TRNTYP'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439575391595280049)
,p_name=>'SUBTTYPE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SUBTTYPE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>60
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P339_SUBTYP'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439576013614280049)
,p_name=>'DOCNUMBR'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCNUMBR'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>70
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'FUNCTION_BODY'
,p_default_language=>'PLSQL'
,p_default_expression=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
' DOCNUM VARCHAR2(100);',
'BEGIN',
'Docnumber_Generation(:compcode, ''AC'', :P339_TRNTYP,:P339_SUBTYP,trunc(sysdate)  ,'''',''AC'', DOCNUM);',
' RETURN DOCNUM;',
'END;'))
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439576600880280052)
,p_name=>'DOCTDATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCTDATE'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>80
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>':P339_DOCTDATE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439577195357280052)
,p_name=>'SERLNUMB'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SERLNUMB'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>90
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P339_SL'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439577786158280052)
,p_name=>'DOCDUEDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCDUEDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>100
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439578451805280054)
,p_name=>'ACCTCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ACCTCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_POPUP_LOV'
,p_heading=>'Account Code'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>110
,p_value_alignment=>'LEFT'
,p_attribute_01=>'DIALOG'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_04=>'N'
,p_is_required=>true
,p_max_length=>30
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT  acctname||''-''||acctcode s, acctcode ',
'    FROM sychrtac',
'   WHERE compcode = :COMPCODE',
'ORDER BY acctcode',
'',
''))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439579071950280054)
,p_name=>'COSTCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'COSTCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SELECT_LIST'
,p_heading=>'Cost Center'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>120
,p_value_alignment=>'LEFT'
,p_is_required=>true
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT j.costdesc S,j.costcode',
'  FROM syjobmas j',
' WHERE compcode = :COMPCODE',
' and j.COSTCODE in (select CABASECC  from sycstacc',
'where Upper(GRUPCODE) = UPPER(:APP_USER))'))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439579671107280054)
,p_name=>'SUBLEDCD'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SUBLEDCD'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>130
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
,p_column_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var $te = $(this.triggeringElement);',
' ',
'//Get the ID of the row',
'var rowId = $te.closest(''tr'').data(''id'');',
' ',
'//Identify the particular interactive grid',
'var ig$ = apex.region("t").widget();',
' ',
'//Fetch the model for the interactive grid',
'var model = ig$.interactiveGrid("getViews","grid").model;',
' ',
'//Fetch the record for the particular rowId',
'var record = model.getRecord(rowId);',
' ',
'//Access the cell value via the column name',
'var DEBIT = model.getValue(record,"DEBIT_AMOUNT");',
'var CREDIT = model.getValue(record,"CREDIT_AMOUNT");',
'var TOTAL = Number(DEBIT)+Number(CREDIT);',
'//Set the values for the JOB and SAL cells',
'model.setValue(record,"JVFCAMNT",TOTAL);',
'',
''))
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439580249222280054)
,p_name=>'TRANCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TRANCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>150
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439580870791280054)
,p_name=>'NARRATION'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'NARATION'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXTAREA'
,p_heading=>'Narration'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>160
,p_value_alignment=>'LEFT'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_is_required=>false
,p_max_length=>200
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439581392112280056)
,p_name=>'DBCRCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DBCRCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>170
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439582055869280056)
,p_name=>'CURRCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CURRCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>180
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P339_CURRCODE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439582682954280057)
,p_name=>'EXCGRATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'EXCGRATE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>190
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P339_EXCGRATE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439583201760280057)
,p_name=>'JVFCAMNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'JVFCAMNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>220
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439583884841280062)
,p_name=>'JVLCAMNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'JVLCAMNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>230
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439584419027280062)
,p_name=>'ORGAMTFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGAMTFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>240
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439585043274280065)
,p_name=>'ORGAMTLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGAMTLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>250
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439585666257280066)
,p_name=>'ADJAMTFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJAMTFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>260
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439586246744280066)
,p_name=>'ADJAMTLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJAMTLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>270
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439586876959280066)
,p_name=>'ORGBAKFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGBAKFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>280
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439587460422280068)
,p_name=>'ORGBAKLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGBAKLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>290
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439588010339280068)
,p_name=>'ADJBAKFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJBAKFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>300
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439588632572280068)
,p_name=>'ADJBAKLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJBAKLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>310
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439589245876280068)
,p_name=>'REFDOCNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDOCNO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>320
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439589787290280070)
,p_name=>'REFDOCDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDOCDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>330
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439590476939280070)
,p_name=>'REFDOCTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDOCTY'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>340
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439591015969280070)
,p_name=>'REFDCSTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDCSTY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>350
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439591657746280070)
,p_name=>'REFDCNUM'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDCNUM'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>360
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439592252905280070)
,p_name=>'REFRDATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFRDATE'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>370
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439592881052280070)
,p_name=>'INTDOCTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDOCTY'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>380
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439593444282280070)
,p_name=>'INTDCSTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDCSTY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>390
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439594075000280070)
,p_name=>'INTDOCNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDOCNO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>400
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439594628617280073)
,p_name=>'INTDOCDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDOCDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>410
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439595276024280073)
,p_name=>'CTRLMCRO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CTRLMCRO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>420
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439595865207280073)
,p_name=>'STATCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'STATCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SELECT_LIST'
,p_heading=>'Post'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>430
,p_value_alignment=>'LEFT'
,p_is_required=>true
,p_lov_type=>'STATIC'
,p_lov_source=>'STATIC:Yes;Y,No;N'
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'STATIC'
,p_default_expression=>'N'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439596459375280073)
,p_name=>'POSTDATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'POSTDATE'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>440
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439596995826280073)
,p_name=>'POSTUSER'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'POSTUSER'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>450
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439597601629280073)
,p_name=>'PURGFLAG'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'PURGFLAG'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>460
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439598256608280073)
,p_name=>'TRANSERL'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TRANSERL'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>470
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439598831643280073)
,p_name=>'ALLCFREZ'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ALLCFREZ'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>480
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439599453441280073)
,p_name=>'CHEQUENO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CHEQUENO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>520
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439600084208280073)
,p_name=>'CHEQUEDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CHEQUEDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>530
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439600601148280074)
,p_name=>'BANKNAME'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BANKNAME'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>490
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439601261822280074)
,p_name=>'BANKBRCH'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BANKBRCH'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>510
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439601787973280074)
,p_name=>'BANKCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BANKCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>500
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439602444217280074)
,p_name=>'EMPLACCT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'EMPLACCT'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>540
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439602999014280074)
,p_name=>'OPRSTAMP'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'OPRSTAMP'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>550
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>':APP_USER'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439603625420280074)
,p_name=>'TIMSTAMP'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TIMSTAMP'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>560
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>'sysdate'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439604193102280074)
,p_name=>'REFSERNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFSERNO'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>570
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439604836756280074)
,p_name=>'ITEMCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ITEMCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>580
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439605444194280080)
,p_name=>'STOKQNTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'STOKQNTY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>590
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439606055393280084)
,p_name=>'MSLCAMNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'MSLCAMNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>600
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439606622072280085)
,p_name=>'REFRBANK'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFRBANK'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>610
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439607214592280085)
,p_name=>'DEPOSTDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DEPOSTDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>620
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439607789522280085)
,p_name=>'REFBNKNM'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFBNKNM'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>630
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(439609590448280087)
,p_name=>'MODIFYDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'MODIFYDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>640
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_interactive_grid(
 p_id=>wwv_flow_api.id(439573029297280031)
,p_internal_uid=>404234939259515629
,p_is_editable=>true
,p_edit_operations=>'i:u:d'
,p_lost_update_check_type=>'VALUES'
,p_add_row_if_empty=>true
,p_submit_checked_rows=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_max_row_count=>100000
,p_show_nulls_as=>'-'
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_toolbar_buttons=>'SEARCH_COLUMN:SEARCH_FIELD:ACTIONS_MENU:SEARCH_COLUMN:SEARCH_FIELD:ACTIONS_MENU:RESET:SAVE'
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>false
,p_enable_mail_download=>true
,p_fixed_header=>'NONE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_api.create_ig_report(
 p_id=>wwv_flow_api.id(439573425061280034)
,p_interactive_grid_id=>wwv_flow_api.id(439573029297280031)
,p_static_id=>'395805'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_api.create_ig_report_view(
 p_id=>wwv_flow_api.id(439573505303280035)
,p_report_id=>wwv_flow_api.id(439573425061280034)
,p_view_type=>'GRID'
,p_stretch_columns=>true
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(127849924582918142)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>0
,p_column_id=>wwv_flow_api.id(127553630322475030)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(127904103734218442)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>66
,p_column_id=>wwv_flow_api.id(127554035699475034)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(129087244843297870)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>67
,p_column_id=>wwv_flow_api.id(128888689974813520)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(206847670528786782)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>13
,p_column_id=>wwv_flow_api.id(206721785401725321)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>109
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(206848341590786801)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>15
,p_column_id=>wwv_flow_api.id(206721829275725322)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>114
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(209380455974079615)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>11
,p_column_id=>wwv_flow_api.id(207955695345146238)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>180
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439574596744280048)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>2
,p_column_id=>wwv_flow_api.id(439574196783280048)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439575280112280048)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>3
,p_column_id=>wwv_flow_api.id(439574881910280048)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439575873842280049)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>4
,p_column_id=>wwv_flow_api.id(439575391595280049)
,p_is_visible=>false
,p_is_frozen=>false
,p_width=>152
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439576455454280052)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>6
,p_column_id=>wwv_flow_api.id(439576013614280049)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>93
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439577060606280052)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>6
,p_column_id=>wwv_flow_api.id(439576600880280052)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>101
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439577597048280052)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>7
,p_column_id=>wwv_flow_api.id(439577195357280052)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439578258102280054)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>8
,p_column_id=>wwv_flow_api.id(439577786158280052)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439578876413280054)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>9
,p_column_id=>wwv_flow_api.id(439578451805280054)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>195
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439579456372280054)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>10
,p_column_id=>wwv_flow_api.id(439579071950280054)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>205
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439580066054280054)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>15
,p_column_id=>wwv_flow_api.id(439579671107280054)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>170
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439580586693280054)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>13
,p_column_id=>wwv_flow_api.id(439580249222280054)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439581282584280056)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>46
,p_column_id=>wwv_flow_api.id(439580870791280054)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>237
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439581806330280056)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>12
,p_column_id=>wwv_flow_api.id(439581392112280056)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>98
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439582485639280056)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>16
,p_column_id=>wwv_flow_api.id(439582055869280056)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439583056442280057)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>17
,p_column_id=>wwv_flow_api.id(439582682954280057)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439583587708280059)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>18
,p_column_id=>wwv_flow_api.id(439583201760280057)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>100
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439584279259280062)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>18
,p_column_id=>wwv_flow_api.id(439583884841280062)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439584830879280063)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>19
,p_column_id=>wwv_flow_api.id(439584419027280062)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439585442652280066)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>20
,p_column_id=>wwv_flow_api.id(439585043274280065)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439586028035280066)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>21
,p_column_id=>wwv_flow_api.id(439585666257280066)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439586634736280066)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>22
,p_column_id=>wwv_flow_api.id(439586246744280066)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439587286091280066)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>23
,p_column_id=>wwv_flow_api.id(439586876959280066)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439587794345280068)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>24
,p_column_id=>wwv_flow_api.id(439587460422280068)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439588424715280068)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>25
,p_column_id=>wwv_flow_api.id(439588010339280068)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439589034149280068)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>26
,p_column_id=>wwv_flow_api.id(439588632572280068)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439589663900280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>27
,p_column_id=>wwv_flow_api.id(439589245876280068)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439590283634280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>28
,p_column_id=>wwv_flow_api.id(439589787290280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439590843961280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>29
,p_column_id=>wwv_flow_api.id(439590476939280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439591437446280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>30
,p_column_id=>wwv_flow_api.id(439591015969280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439592034584280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>31
,p_column_id=>wwv_flow_api.id(439591657746280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439592660705280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>32
,p_column_id=>wwv_flow_api.id(439592252905280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439593254052280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>33
,p_column_id=>wwv_flow_api.id(439592881052280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439593800956280070)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>34
,p_column_id=>wwv_flow_api.id(439593444282280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439594468314280071)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>35
,p_column_id=>wwv_flow_api.id(439594075000280070)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439595040406280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>36
,p_column_id=>wwv_flow_api.id(439594628617280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439595647510280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>37
,p_column_id=>wwv_flow_api.id(439595276024280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439596202346280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>38
,p_column_id=>wwv_flow_api.id(439595865207280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439596867079280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>39
,p_column_id=>wwv_flow_api.id(439596459375280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439597460244280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>40
,p_column_id=>wwv_flow_api.id(439596995826280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439598072040280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>41
,p_column_id=>wwv_flow_api.id(439597601629280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439598655771280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>42
,p_column_id=>wwv_flow_api.id(439598256608280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439599233006280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>43
,p_column_id=>wwv_flow_api.id(439598831643280073)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439599883723280073)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>51
,p_column_id=>wwv_flow_api.id(439599453441280073)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>119
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439600444506280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>65
,p_column_id=>wwv_flow_api.id(439600084208280073)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>91
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439601031816280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>46
,p_column_id=>wwv_flow_api.id(439600601148280074)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439601588065280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>49
,p_column_id=>wwv_flow_api.id(439601261822280074)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>138
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439602235990280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>48
,p_column_id=>wwv_flow_api.id(439601787973280074)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>165
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439602826373280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>49
,p_column_id=>wwv_flow_api.id(439602444217280074)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439603423679280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>50
,p_column_id=>wwv_flow_api.id(439602999014280074)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439603991615280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>51
,p_column_id=>wwv_flow_api.id(439603625420280074)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439604667078280074)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>52
,p_column_id=>wwv_flow_api.id(439604193102280074)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439605190927280080)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>53
,p_column_id=>wwv_flow_api.id(439604836756280074)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439605788872280084)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>54
,p_column_id=>wwv_flow_api.id(439605444194280080)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439606477176280085)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>55
,p_column_id=>wwv_flow_api.id(439606055393280084)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439607025665280085)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>56
,p_column_id=>wwv_flow_api.id(439606622072280085)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439607629874280085)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>57
,p_column_id=>wwv_flow_api.id(439607214592280085)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439608188904280087)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>58
,p_column_id=>wwv_flow_api.id(439607789522280085)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(439610013996280087)
,p_view_id=>wwv_flow_api.id(439573505303280035)
,p_display_seq=>61
,p_column_id=>wwv_flow_api.id(439609590448280087)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(38155510967597236)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(206724012827725343)
,p_button_name=>'rcv_paya'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Opening for Recevibale & Payable'
,p_button_position=>'BELOW_BOX'
,p_button_redirect_url=>'f?p=&APP_ID.:351:&SESSION.::&DEBUG.:RP::'
,p_button_condition_type=>'NEVER'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(38155964810597236)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_api.id(206724012827725343)
,p_button_name=>'CREATE'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'BELOW_BOX'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(38156355182597236)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_api.id(206724012827725343)
,p_button_name=>'Clear'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Clear'
,p_button_position=>'BELOW_BOX'
,p_button_redirect_url=>'f?p=&APP_ID.:339:&SESSION.::&DEBUG.:RP,294::'
,p_button_condition_type=>'NEVER'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(38156780980597236)
,p_button_sequence=>40
,p_button_plug_id=>wwv_flow_api.id(206724012827725343)
,p_button_name=>'Cancel'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Cancel'
,p_button_position=>'BELOW_BOX'
,p_button_redirect_url=>'f?p=&APP_ID.:344:&SESSION.::&DEBUG.:RP,343::'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(38157172363597236)
,p_button_sequence=>50
,p_button_plug_id=>wwv_flow_api.id(206724012827725343)
,p_button_name=>'Search'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--stretch'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Add'
,p_button_position=>'BELOW_BOX'
,p_button_condition_type=>'NEVER'
,p_button_cattributes=>'style = "width:80px;"'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38148133183597234)
,p_name=>'P339_TRANTYPE'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38148555139597234)
,p_name=>'P339_SUBTTYPE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38148938362597234)
,p_name=>'P339_PRDOCTYP'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38149381878597234)
,p_name=>'P339_PRSUBTYP'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38149712339597234)
,p_name=>'P339_NARATION'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38150131431597234)
,p_name=>'P339_TRNTYP'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38150515337597234)
,p_name=>'P339_SUBTYP'
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38150952393597235)
,p_name=>'P339_TRTRNTYP'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38151383758597235)
,p_name=>'P339_TRSUBTYP'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38151784331597235)
,p_name=>'P339_NARATION_1'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38152145064597235)
,p_name=>'P339_SATVAL'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_api.id(439572535643280021)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38153678572597235)
,p_name=>'P339_BANK_CODE'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(206720383128725307)
,p_prompt=>'Bank Name'
,p_display_as=>'NATIVE_POPUP_LOV'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select LPAD(''SELECT BANK'',50,''#'') b,'''' BANKCODE',
'from DUAL',
'UNION ALL',
'select distinct W.BANKNAME b,W.BANKCODE',
'from ACBNKVW w',
'where W.COMPCODE = :compcode',
''))
,p_lov_display_null=>'YES'
,p_cSize=>40
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'DIALOG'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_04=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38154011771597236)
,p_name=>'P339_BANK_BRANCH'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_api.id(206720383128725307)
,p_prompt=>'Bank Branch'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>100
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38154483277597236)
,p_name=>'P339_CHEQUE_NO'
,p_item_sequence=>120
,p_item_plug_id=>wwv_flow_api.id(206720383128725307)
,p_prompt=>'Cheque No'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_colspan=>6
,p_grid_column=>1
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38154808787597236)
,p_name=>'P339_DATE'
,p_item_sequence=>130
,p_item_plug_id=>wwv_flow_api.id(206720383128725307)
,p_prompt=>'Date'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>12
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>1
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38157878176597236)
,p_name=>'P339_DOCNUMBR'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_prompt=>'Document No'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_grid_label_column_span=>1
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38158213128597236)
,p_name=>'P339_DOCTDATE'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_item_default=>'sysdate'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_prompt=>'Date'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>50
,p_cMaxlength=>4000
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>1
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38158649857597237)
,p_name=>'P339_YERCDE'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_prompt=>'Year Code'
,p_display_as=>'NATIVE_AUTO_COMPLETE'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Select Distinct  YEARCODE',
'From Accompar',
'Where COMPCODE=:COMPCODE',
'Order By YEARCODE Desc'))
,p_cSize=>30
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>1
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'CONTAINS_IGNORE'
,p_attribute_04=>'N'
,p_attribute_06=>'N'
,p_attribute_07=>'Y'
,p_attribute_08=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38159014985597237)
,p_name=>'P339_GRANDDRTOTAL'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38159422692597237)
,p_name=>'P339_GRANDCRTOTAL'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38159851714597237)
,p_name=>'P339_GRANDCRTOTAL_1'
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38160205128597237)
,p_name=>'P339_SL'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
's_sl number;',
'begin',
' select count(*)+1',
'  into s_sl',
'  from actrndtl;',
'  return s_sl;',
'end;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38160613855597237)
,p_name=>'P339_SUBLEDGER'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38161022757597237)
,p_name=>'P339_CURRCODE'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
' co_curr varchar2(3);',
'Begin',
'    Select nvl(calcrcde,''DHS'') into co_curr from syparmas',
'     where cacmpcde = :compcode;',
'      return co_curr;',
'Exception',
'    When no_data_found then',
'     co_curr := null;',
'     return co_curr;',
'    When too_many_rows then',
'     co_curr := null;',
'     return co_curr;',
'End;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38161459215597237)
,p_name=>'P339_TOTAL'
,p_item_sequence=>120
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
' co_curr varchar2(3);',
'Begin',
'    Select nvl(calcrcde,''DHS'') into co_curr from syparmas',
'     where cacmpcde = :compcode;',
'      return co_curr;',
'Exception',
'    When no_data_found then',
'     co_curr := null;',
'     return co_curr;',
'    When too_many_rows then',
'     co_curr := null;',
'     return co_curr;',
'End;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38161837090597237)
,p_name=>'P339_EXCGRATE'
,p_item_sequence=>130
,p_item_plug_id=>wwv_flow_api.id(312741041025152169)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
'      s_exgrte number;',
'    BEGIN',
'      Select CACONVRT INTO  s_exgrte From sycurmas',
'      where  cacurcde in (Select nvl(calcrcde,''DHS'') ',
'                           from syparmas',
'                          where cacmpcde = :compcode) ',
'        and  rownum   =1;',
'        return s_exgrte;',
'  Exception',
'        When no_data_found then',
'         s_exgrte := null;',
'         return s_exgrte;',
'        When too_many_rows then',
'         s_exgrte := null;',
'         return s_exgrte;',
'        When others then',
'         s_exgrte := null;',
'         return s_exgrte;',
'End;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38162505055597237)
,p_name=>'P339_REFNUMBR'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_prompt=>'Reference'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>26
,p_cMaxlength=>4000
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38162924008597237)
,p_name=>'P339_REFDATE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_prompt=>'Ref. Date'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>26
,p_cMaxlength=>4000
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38163356992597238)
,p_name=>'P339_BANKCASHHEAD'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38163753508597238)
,p_name=>'P339_CRDRCD'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38164102460597238)
,p_name=>'P339_COSTCODE'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_prompt=>'Cost Code'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT j.costdesc S,j.costcode',
'  FROM syjobmas j',
' WHERE compcode = :COMPCODE',
' and j.COSTCODE in (select CABASECC  from sycstacc',
'where Upper(GRUPCODE) = UPPER(:APP_USER))'))
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38164549846597238)
,p_name=>'P339_COSTCODE_1'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38164982012597238)
,p_name=>'P339_AMOUNT'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(38165351744597238)
,p_name=>'P339_SATFLG'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(327045736903243788)
,p_item_default=>'N'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38180101989597241)
,p_name=>'set_code_default'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38180658584597241)
,p_event_id=>wwv_flow_api.id(38180101989597241)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_EXECUTE_PLSQL_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'   CURSOR C',
'   IS',
'      SELECT DFLTACCT, DFLTDBCR DBCRCODE, LOCNCODE',
'        FROM sydocmas',
'       WHERE     compcode = :compcode',
'             AND MODLCODE = ''AC''',
'             AND TRANTYPE = :P339_TRNTYP',
'             AND SUBTTYPE = :P339_SUBTYP;',
'',
'   REC   C%ROWTYPE;',
'BEGIN',
'   OPEN C;',
'',
'   FETCH C INTO REC;',
'',
'   CLOSE C;',
'   if  REC.DFLTACCT is not null then',
'   :P339_BANKCASHHEAD := REC.DFLTACCT;',
'   end if;',
'   if  REC.DBCRCODE is not null then',
'   :P339_CRDRCD := REC.DBCRCODE;',
'   end if;',
'',
'   DECLARE',
'      CURSOR c_cost',
'      IS',
'         SELECT J.COSTCODE',
'           FROM nmwhsmas j',
'          WHERE J.COMPCODE = :compcode AND J.WARECODE = rec.LOCNCODE;',
'',
'      costc   c_cost%ROWTYPE;',
'   BEGIN',
'  ',
'      OPEN c_cost;',
'',
'      FETCH c_cost INTO costc;',
'',
'      CLOSE c_cost;',
'      if costc.COSTCODE is not null then',
'      :P339_COSTCODE_1 := costc.COSTCODE;',
'      end if;',
'   END;',
'END;'))
,p_attribute_02=>'P339_TRNTYP,P339_SUBTYP'
,p_attribute_03=>'P339_COSTCODE_1,P339_BANKCASHHEAD,P339_CRDRCD'
,p_attribute_04=>'N'
,p_attribute_05=>'PLSQL'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38181079944597241)
,p_name=>'set_val'
,p_event_sequence=>20
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'COSTCODE'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38181508998597241)
,p_event_id=>wwv_flow_api.id(38181079944597241)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'COSTCODE'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vcost varchar2(100);',
'begin',
' if :P339_COSTCODE_1 is not null then',
'  vcost := :P339_COSTCODE_1;',
' else',
'  vcost := :P339_COSTCODE;',
' end if;',
'  return vcost;',
'end;'))
,p_attribute_07=>'P339_COSTCODE'
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38167774939597239)
,p_name=>'set_debit'
,p_event_sequence=>30
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'DEBIT_AMOUNT'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38168265292597239)
,p_event_id=>wwv_flow_api.id(38167774939597239)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DEBIT_AMOUNT'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vcost number;',
'begin',
'  return 0;',
'end;'))
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38168602884597239)
,p_name=>'set_credit'
,p_event_sequence=>40
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'CREDIT_AMOUNT'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38169153914597239)
,p_event_id=>wwv_flow_api.id(38168602884597239)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'CREDIT_AMOUNT'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vcost number;',
'begin',
'  return 0;',
'end;'))
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38169545999597239)
,p_name=>'show_col'
,p_event_sequence=>50
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_condition_element_type=>'ITEM'
,p_condition_element=>'P339_CRDRCD'
,p_triggering_condition_type=>'NOT_NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
,p_display_when_type=>'NEVER'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38170052373597239)
,p_event_id=>wwv_flow_api.id(38169545999597239)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_DISABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DBCRCODE'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38170511981597239)
,p_event_id=>wwv_flow_api.id(38169545999597239)
,p_event_result=>'FALSE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_ENABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DBCRCODE'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38170955785597239)
,p_name=>'sum_total'
,p_event_sequence=>60
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(38155964810597236)
,p_bind_type=>'bind'
,p_bind_event_type=>'click'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38171391759597239)
,p_event_id=>wwv_flow_api.id(38170955785597239)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P339_GRANDDRTOTAL'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'    var sumSAL = 0;  ',
'    var sal = 0;  ',
'    $(''.debit'').each(function() {  ',
'        sal = parseInt($(this).html());  ',
'        if (isNaN(sal)) ',
'            {',
'               sal = 0;  ',
'            }',
'        else',
'            {',
'               sal = parseInt($(this).html());  ',
'            }',
'        sumSAL = sumSAL + sal;  ',
'    });  ',
'    $s(''P339_GRANDDRTOTAL'',sumSAL); ',
'',
' '))
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38171911837597239)
,p_event_id=>wwv_flow_api.id(38170955785597239)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P339_GRANDCRTOTAL'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'    var sumSAL = 0;  ',
'    var sal = 0;  ',
'    $(''.credit'').each(function() {  ',
'        sal = parseInt($(this).html());  ',
'         if (isNaN(sal)) ',
'            {',
'               sal=0; ',
'            }',
'         else',
'            {',
'               sal = parseInt($(this).html());  ',
'            }',
'        sumSAL = sumSAL + sal;  ',
'    });  ',
'    $s(''P339_GRANDCRTOTAL'',sumSAL);  ',
'',
'',
'     '))
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38172485308597239)
,p_event_id=>wwv_flow_api.id(38170955785597239)
,p_event_result=>'TRUE'
,p_action_sequence=>30
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SUBMIT_PAGE'
,p_attribute_02=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38172836756597239)
,p_name=>'check_costcd'
,p_event_sequence=>70
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'ITEM'
,p_condition_element=>'P339_COSTCODE'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
,p_display_when_type=>'NEVER'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38173322074597240)
,p_event_id=>wwv_flow_api.id(38172836756597239)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P339_SATVAL'
,p_attribute_01=>'STATIC_ASSIGNMENT'
,p_attribute_02=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38173738413597240)
,p_name=>'show_mess'
,p_event_sequence=>80
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P339_SATVAL'
,p_condition_element=>'P339_SATVAL'
,p_triggering_condition_type=>'EQUALS'
,p_triggering_expression=>'Y'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38174238450597240)
,p_event_id=>wwv_flow_api.id(38173738413597240)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_ALERT'
,p_attribute_01=>'&#x27;ERROR: Cost center cannot be blank...&#x27;'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38174636180597240)
,p_name=>'set_cs'
,p_event_sequence=>90
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P339_COSTCODE_1'
,p_condition_element=>'P339_COSTCODE_1'
,p_triggering_condition_type=>'NOT_NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38175148308597240)
,p_event_id=>wwv_flow_api.id(38174636180597240)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P339_COSTCODE'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
'  return :P339_COSTCODE_1;',
'end;'))
,p_attribute_07=>'P339_COSTCODE_1'
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38175579331597240)
,p_name=>'CONFIRM'
,p_event_sequence=>100
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P339_SHOW_ALT'
,p_condition_element=>'P339_SHOW_ALT'
,p_triggering_condition_type=>'EQUALS'
,p_triggering_expression=>'Y'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38176035613597240)
,p_event_id=>wwv_flow_api.id(38175579331597240)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_ALERT'
,p_attribute_01=>'ERROR: Debit Credit Amount Mismatch........'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38176429775597240)
,p_name=>'set_credit_disable'
,p_event_sequence=>110
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_triggering_element=>'DEBIT_AMOUNT'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'DEBIT_AMOUNT'
,p_triggering_condition_type=>'GREATER_THAN'
,p_triggering_expression=>'0'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38176893842597240)
,p_event_id=>wwv_flow_api.id(38176429775597240)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_DISABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'CREDIT_AMOUNT'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38177394025597240)
,p_event_id=>wwv_flow_api.id(38176429775597240)
,p_event_result=>'FALSE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_ENABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'CREDIT_AMOUNT'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38177855772597240)
,p_name=>'set_debit_disable'
,p_event_sequence=>120
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(439572535643280021)
,p_triggering_element=>'CREDIT_AMOUNT'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'CREDIT_AMOUNT'
,p_triggering_condition_type=>'GREATER_THAN'
,p_triggering_expression=>'0'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38178295169597240)
,p_event_id=>wwv_flow_api.id(38177855772597240)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_DISABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DEBIT_AMOUNT'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38178846669597240)
,p_event_id=>wwv_flow_api.id(38177855772597240)
,p_event_result=>'FALSE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_ENABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DEBIT_AMOUNT'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(38179247536597240)
,p_name=>'New'
,p_event_sequence=>130
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(38179787163597241)
,p_event_id=>wwv_flow_api.id(38179247536597240)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_CLEAR'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P339_DOCNUMBR'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38167350333597238)
,p_process_sequence=>100
,p_process_point=>'AFTER_FOOTER'
,p_process_type=>'NATIVE_SESSION_STATE'
,p_process_name=>'set_det'
,p_attribute_01=>'CLEAR_CACHE_FOR_ITEMS'
,p_attribute_03=>'P339_DOCNUMBR,P339_COSTCODE,P339_GRANDDRTOTAL,P339_GRANDCRTOTAL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_type=>'NEVER'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38166164425597238)
,p_process_sequence=>40
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'INSERT_OLTERNATE_RECORD'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'IF :P339_DOCNUMBR IS NOT NULL THEN',
'insert into actrndtl (COMPCODE,DOCTTYPE,SUBTTYPE,DOCNUMBR,DOCTDATE,SERLNUMB,ACCTCODE,COSTCODE,SUBLEDCD,DBCRCODE,CURRCODE,',
'EXCGRATE,JVFCAMNT,JVLCAMNT,ORGAMTFC,ORGAMTLC,STATCODE,OPRSTAMP,TIMSTAMP)',
'values(:compcode,:P339_TRNTYP,:P339_SUBTYP,:P339_DOCNUMBR,TRUNC(SYSDATE),:P339_SL,:P339_BANKCASHHEAD,:P339_COSTCODE,:P339_SUBLEDGER,',
':P339_CRDRCD,:P339_CURRCODE,:P339_EXCGRATE,:P339_AMOUNT,:P339_AMOUNT,:P339_AMOUNT,:P339_AMOUNT,''N'',:APP_USER,SYSDATE);',
'COMMIT;',
'END IF;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_type=>'NEVER'
,p_process_success_message=>'Transaction No generated successfully..:&P339_DOCNUMBR_1.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38152507636597235)
,p_process_sequence=>50
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_api.id(439572535643280021)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'Opening Balance - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_success_message=>'Transaction No generated successfully..:&P339_DOCNUMBR.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38165712290597238)
,p_process_sequence=>20
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'check_amt_validation'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vtotal number;',
'begin',
'if nvl(to_number(:P339_GRANDDRTOTAL),0) <> nvl(to_number(:P339_GRANDCRTOTAL),0) then',
'raise_application_error(-20001,''Debit Credit amount mismatch...'');',
'end if;',
'end;',
''))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38166940879597238)
,p_process_sequence=>40
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GEN_DOC'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' DOCNUM varchar2(100);',
'    begin',
'           Docnumber_Generation(:compcode, ''AC'', :P339_TRNTYP,:P339_SUBTYP,trunc(sysdate)  ,'''',''AC'', DOCNUM);',
'        :P339_DOCNUMBR:=DOCNUM;',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_type=>'NEVER'
,p_process_is_stateful_y_n=>'Y'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38152934653597235)
,p_process_sequence=>60
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_region_id=>wwv_flow_api.id(439572535643280021)
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'pre_insert'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
' :P339_DOCNUMBR := :DOCNUMBR;',
' :JVFCAMNT := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);',
' :ORGAMTFC := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);',
' :ORGAMTLC := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);',
' :SUBLEDCD := :CUSTOMER;',
' :YEARCODE := :P339_YERCDE;',
'/* :BANKCODE := :P339_BANK_CODE;',
' :BANKBRCH := :P339_BANK_BRANCH;',
' :CHEQUENO := :P339_CHEQUE_NO;',
' :CHEQUEDT := :P339_DATE;*/',
' if :DEBIT_AMOUNT>0 then',
'  :DBCRCODE:=''D'';',
' end if;',
' if :CREDIT_AMOUNT>0 then',
'  :DBCRCODE:=''C'';',
' end if;',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(38166571534597238)
,p_process_sequence=>60
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'post'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
':P339_SATFLG := ''Y'';',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_api.id(38155964810597236)
);
wwv_flow_api.component_end;
end;
/
