prompt --application/pages/page_00369
begin
--   Manifest
--     PAGE: 00369
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>369
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>'Journal Entry'
,p_page_mode=>'MODAL'
,p_step_title=>'Journal Entry'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'GADMIN'
,p_last_upd_yyyymmddhh24miss=>'20180719113611'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(126013353243901684)
,p_plug_name=>'Bank Details'
,p_region_template_options=>'#DEFAULT#:i-h100:t-Region--removeHeader:t-Region--hiddenOverflow:t-Form--leftLabels'
,p_region_attributes=>'style="background-color:&BACKGROUND_COLOR.;"'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>60
,p_plug_new_grid_row=>false
,p_plug_grid_column_span=>4
,p_plug_display_column=>9
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(126016982942901720)
,p_plug_name=>'Button_region'
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--noBorder:t-Region--hiddenOverflow:t-Form--stretchInputs'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'REGION_POSITION_03'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(232034011140328546)
,p_plug_name=>'B'
,p_region_template_options=>'#DEFAULT#:i-h100:t-Region--removeHeader:t-Region--hiddenOverflow:t-Form--leftLabels'
,p_region_attributes=>'style="background-color:&BACKGROUND_COLOR.;"'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>30
,p_plug_grid_column_span=>4
,p_plug_display_column=>1
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(246338707018420165)
,p_plug_name=>'A'
,p_region_template_options=>'#DEFAULT#:i-h100:t-Region--removeHeader:t-Region--hiddenOverflow:t-Form--leftLabels'
,p_component_template_options=>'#DEFAULT#'
,p_region_attributes=>'style="background-color:&BACKGROUND_COLOR.;"'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>50
,p_plug_new_grid_row=>false
,p_plug_grid_column_span=>4
,p_plug_display_column=>5
,p_plug_item_display_point=>'BELOW'
,p_plug_query_headings_type=>'QUERY_COLUMNS'
,p_plug_query_num_rows_type=>'NEXT_PREVIOUS_LINKS'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_plug_query_show_nulls_as=>' - '
,p_pagination_display_position=>'BOTTOM_RIGHT'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(358865505758456398)
,p_plug_name=>'Journal Entry'
,p_region_name=>'t'
,p_region_template_options=>'#DEFAULT#:t-Region--hiddenOverflow'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(47588528672858186)
,p_plug_display_sequence=>80
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select COMPCODE,',
'       DOCTTYPE,',
'       SUBTTYPE,',
'       DOCNUMBR,',
'       DOCTDATE,',
'       SERLNUMB,',
'       DOCDUEDT,',
'       ACCTCODE,',
'       COSTCODE,',
'       SUBLEDCD,',
'       TRANCODE,',
'       NARATION,',
'       DBCRCODE,',
'       CURRCODE,',
'       EXCGRATE,',
'       JVFCAMNT,',
'       JVLCAMNT,',
'       ORGAMTFC,',
'       ORGAMTLC,',
'       ADJAMTFC,',
'       ADJAMTLC,',
'       ORGBAKFC,',
'       ORGBAKLC,',
'       ADJBAKFC,',
'       ADJBAKLC,',
'       REFDOCNO,',
'       REFDOCDT,',
'       REFDOCTY,',
'       REFDCSTY,',
'       REFDCNUM,',
'       REFRDATE,',
'       INTDOCTY,',
'       INTDCSTY,',
'       INTDOCNO,',
'       INTDOCDT,',
'       CTRLMCRO,',
'       STATCODE,',
'       POSTDATE,',
'       POSTUSER,',
'       PURGFLAG,',
'       TRANSERL,',
'       ALLCFREZ,',
'       CHEQUENO,',
'       CHEQUEDT,',
'       BANKNAME,',
'       BANKBRCH,',
'       BANKCODE,',
'       EMPLACCT,',
'       OPRSTAMP,',
'       TIMSTAMP,',
'       REFSERNO,',
'       ITEMCODE,',
'       STOKQNTY,',
'       MSLCAMNT,',
'       REFRBANK,',
'       DEPOSTDT,',
'       REFBNKNM,',
'       CHRGTYPE,',
'       REFPERSN,',
'       MODIFYDT,',
'       TOPREFNO,',
'       0 Debit_Amount,',
'       0 Credit_Amount,',
'       '''' customer',
'  from ACTRNDTL',
'   where compcode = :compcode',
'  and DOCTTYPE = :P296_TRANTYPE',
'  and SUBTTYPE = :P296_SUBTTYPE',
'  and ACCTCODE is null'))
,p_plug_source_type=>'NATIVE_IG'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(126014755516901698)
,p_name=>'DEBIT_AMOUNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DEBIT_AMOUNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>true
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Debit Amount'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>200
,p_value_alignment=>'CENTER'
,p_value_css_classes=>'debit'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(126014799390901699)
,p_name=>'CREDIT_AMOUNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CREDIT_AMOUNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>true
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Credit Amount'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>210
,p_value_alignment=>'CENTER'
,p_value_css_classes=>'credit'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(126688215614808526)
,p_name=>'APEX$ROW_ACTION'
,p_item_type=>'NATIVE_ROW_ACTION'
,p_display_sequence=>20
,p_enable_hide=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(126688375105808527)
,p_name=>'APEX$ROW_SELECTOR'
,p_item_type=>'NATIVE_ROW_SELECTOR'
,p_display_sequence=>10
,p_attribute_01=>'Y'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
,p_enable_hide=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(127248665460322615)
,p_name=>'CUSTOMER'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CUSTOMER'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_POPUP_LOV'
,p_heading=>'Customer'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>140
,p_value_alignment=>'LEFT'
,p_attribute_01=>'DIALOG'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_04=>'N'
,p_is_required=>false
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT prtyname CUSTNAME,partycde',
'    FROM sycompty',
'   WHERE compcode = :COMPCODE ',
'   AND NVL (partysts, 1) != 8',
'   ORDER BY 1'))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358866676622456417)
,p_name=>'ROWID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ROWID'
,p_data_type=>'ROWID'
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>30
,p_attribute_01=>'Y'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358867166898456425)
,p_name=>'COMPCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'COMPCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>40
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>':compcode'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358867852025456425)
,p_name=>'DOCTTYPE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCTTYPE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>50
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P369_TRNTYP'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358868361710456426)
,p_name=>'SUBTTYPE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SUBTTYPE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>60
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P369_SUBTYP'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358868983729456426)
,p_name=>'DOCNUMBR'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCNUMBR'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>70
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'FUNCTION_BODY'
,p_default_language=>'PLSQL'
,p_default_expression=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
' DOCNUM VARCHAR2(100);',
'BEGIN',
'Docnumber_Generation(:compcode, ''AC'', :P369_TRNTYP,:P369_SUBTYP,trunc(sysdate)  ,'''',''AC'', DOCNUM);',
' RETURN DOCNUM;',
'END;'))
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358869570995456429)
,p_name=>'DOCTDATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCTDATE'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>80
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>':P369_DOCTDATE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358870165472456429)
,p_name=>'SERLNUMB'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SERLNUMB'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>90
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P369_SL'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358870756273456429)
,p_name=>'DOCDUEDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DOCDUEDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>100
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358871421920456431)
,p_name=>'ACCTCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ACCTCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_POPUP_LOV'
,p_heading=>'Account Code'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>110
,p_value_alignment=>'LEFT'
,p_attribute_01=>'DIALOG'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_04=>'N'
,p_is_required=>true
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT  acctname||''-''||acctcode s, acctcode ',
'    FROM sychrtac',
'   WHERE compcode = :COMPCODE',
'    and nvl(HEADFLAG,''Y'') = ''N''',
'ORDER BY acctcode'))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358872042065456431)
,p_name=>'COSTCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'COSTCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SELECT_LIST'
,p_heading=>'Cost Center'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>120
,p_value_alignment=>'LEFT'
,p_is_required=>true
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT j.costdesc S,j.costcode',
'  FROM syjobmas j',
' WHERE compcode = :COMPCODE',
' and j.COSTCODE in (select CABASECC  from sycstacc',
'where Upper(GRUPCODE) = UPPER(:APP_USER))'))
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'LOV'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358872641222456431)
,p_name=>'SUBLEDCD'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SUBLEDCD'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>130
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
,p_column_comment=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var $te = $(this.triggeringElement);',
' ',
'//Get the ID of the row',
'var rowId = $te.closest(''tr'').data(''id'');',
' ',
'//Identify the particular interactive grid',
'var ig$ = apex.region("t").widget();',
' ',
'//Fetch the model for the interactive grid',
'var model = ig$.interactiveGrid("getViews","grid").model;',
' ',
'//Fetch the record for the particular rowId',
'var record = model.getRecord(rowId);',
' ',
'//Access the cell value via the column name',
'var DEBIT = model.getValue(record,"DEBIT_AMOUNT");',
'var CREDIT = model.getValue(record,"CREDIT_AMOUNT");',
'var TOTAL = Number(DEBIT)+Number(CREDIT);',
'//Set the values for the JOB and SAL cells',
'model.setValue(record,"JVFCAMNT",TOTAL);',
'',
''))
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358873219337456431)
,p_name=>'TRANCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TRANCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>150
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358873840906456431)
,p_name=>'NARATION'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'NARATION'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXTAREA'
,p_heading=>'Narration'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>160
,p_value_alignment=>'LEFT'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_is_required=>false
,p_max_length=>500
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358874362227456433)
,p_name=>'DBCRCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DBCRCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>170
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358875025984456433)
,p_name=>'CURRCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CURRCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>180
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P369_CURRCODE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358875653069456434)
,p_name=>'EXCGRATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'EXCGRATE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>190
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'P369_EXCGRATE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358876171875456434)
,p_name=>'JVFCAMNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'JVFCAMNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>220
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358876854956456439)
,p_name=>'JVLCAMNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'JVLCAMNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>230
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358877389142456439)
,p_name=>'ORGAMTFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGAMTFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>240
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358878013389456442)
,p_name=>'ORGAMTLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGAMTLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>250
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358878636372456443)
,p_name=>'ADJAMTFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJAMTFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>260
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358879216859456443)
,p_name=>'ADJAMTLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJAMTLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>270
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358879847074456443)
,p_name=>'ORGBAKFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGBAKFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>280
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358880430537456445)
,p_name=>'ORGBAKLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ORGBAKLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>290
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358880980454456445)
,p_name=>'ADJBAKFC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJBAKFC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>300
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358881602687456445)
,p_name=>'ADJBAKLC'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ADJBAKLC'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>310
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358882215991456445)
,p_name=>'REFDOCNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDOCNO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>320
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358882757405456447)
,p_name=>'REFDOCDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDOCDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>330
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358883447054456447)
,p_name=>'REFDOCTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDOCTY'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>340
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358883986084456447)
,p_name=>'REFDCSTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDCSTY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>350
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358884627861456447)
,p_name=>'REFDCNUM'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFDCNUM'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>360
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358885223020456447)
,p_name=>'REFRDATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFRDATE'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>370
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358885851167456447)
,p_name=>'INTDOCTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDOCTY'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>380
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358886414397456447)
,p_name=>'INTDCSTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDCSTY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>390
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358887045115456447)
,p_name=>'INTDOCNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDOCNO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>400
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358887598732456450)
,p_name=>'INTDOCDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'INTDOCDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>410
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358888246139456450)
,p_name=>'CTRLMCRO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CTRLMCRO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>420
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358888835322456450)
,p_name=>'STATCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'STATCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>430
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'STATIC'
,p_default_expression=>'N'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358889429490456450)
,p_name=>'POSTDATE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'POSTDATE'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>440
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358889965941456450)
,p_name=>'POSTUSER'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'POSTUSER'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>450
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358890571744456450)
,p_name=>'PURGFLAG'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'PURGFLAG'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>460
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358891226723456450)
,p_name=>'TRANSERL'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TRANSERL'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>470
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358891801758456450)
,p_name=>'ALLCFREZ'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ALLCFREZ'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>480
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358892423556456450)
,p_name=>'CHEQUENO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CHEQUENO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>520
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358893054323456450)
,p_name=>'CHEQUEDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CHEQUEDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>530
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358893571263456451)
,p_name=>'BANKNAME'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BANKNAME'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>490
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358894231937456451)
,p_name=>'BANKBRCH'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BANKBRCH'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>510
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358894758088456451)
,p_name=>'BANKCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BANKCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>500
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358895414332456451)
,p_name=>'EMPLACCT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'EMPLACCT'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>540
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358895969129456451)
,p_name=>'OPRSTAMP'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'OPRSTAMP'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>550
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>':APP_USER'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358896595535456451)
,p_name=>'TIMSTAMP'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TIMSTAMP'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>560
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_default_type=>'EXPRESSION'
,p_default_language=>'PLSQL'
,p_default_expression=>'sysdate'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358897163217456451)
,p_name=>'REFSERNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFSERNO'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>570
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358897806871456451)
,p_name=>'ITEMCODE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ITEMCODE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>580
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358898414309456457)
,p_name=>'STOKQNTY'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'STOKQNTY'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>590
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358899025508456461)
,p_name=>'MSLCAMNT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'MSLCAMNT'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>600
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358899592187456462)
,p_name=>'REFRBANK'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFRBANK'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>610
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358900184707456462)
,p_name=>'DEPOSTDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DEPOSTDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>620
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358900759637456462)
,p_name=>'REFBNKNM'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFBNKNM'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>630
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358901385887456464)
,p_name=>'CHRGTYPE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CHRGTYPE'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>640
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358901986816456464)
,p_name=>'REFPERSN'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'REFPERSN'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>650
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_control_break=>false
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358902560563456464)
,p_name=>'MODIFYDT'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'MODIFYDT'
,p_data_type=>'DATE'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>660
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(358903224278456464)
,p_name=>'TOPREFNO'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'TOPREFNO'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>670
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_enable_pivot=>false
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_interactive_grid(
 p_id=>wwv_flow_api.id(358865999412456408)
,p_internal_uid=>323527909374692006
,p_is_editable=>true
,p_edit_operations=>'i:u'
,p_lost_update_check_type=>'VALUES'
,p_add_row_if_empty=>true
,p_submit_checked_rows=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_max_row_count=>100000
,p_show_nulls_as=>'-'
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_toolbar_buttons=>'SEARCH_COLUMN:SEARCH_FIELD:ACTIONS_MENU:RESET'
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>false
,p_download_formats=>null
,p_enable_mail_download=>true
,p_fixed_header=>'NONE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_api.create_ig_report(
 p_id=>wwv_flow_api.id(358866395176456411)
,p_interactive_grid_id=>wwv_flow_api.id(358865999412456408)
,p_static_id=>'395857'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_api.create_ig_report_view(
 p_id=>wwv_flow_api.id(358866475418456412)
,p_report_id=>wwv_flow_api.id(358866395176456411)
,p_view_type=>'GRID'
,p_stretch_columns=>true
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(126140640643963159)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>13
,p_column_id=>wwv_flow_api.id(126014755516901698)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>109
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(126141311705963178)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>15
,p_column_id=>wwv_flow_api.id(126014799390901699)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>114
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(127547955706322845)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>0
,p_column_id=>wwv_flow_api.id(126688215614808526)
,p_is_visible=>true
,p_is_frozen=>true
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(128673426089255992)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>11
,p_column_id=>wwv_flow_api.id(127248665460322615)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>180
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358867052747456422)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>1
,p_column_id=>wwv_flow_api.id(358866676622456417)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358867566859456425)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>2
,p_column_id=>wwv_flow_api.id(358867166898456425)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358868250227456425)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>3
,p_column_id=>wwv_flow_api.id(358867852025456425)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358868843957456426)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>4
,p_column_id=>wwv_flow_api.id(358868361710456426)
,p_is_visible=>false
,p_is_frozen=>false
,p_width=>152
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358869425569456429)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>6
,p_column_id=>wwv_flow_api.id(358868983729456426)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>93
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358870030721456429)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>6
,p_column_id=>wwv_flow_api.id(358869570995456429)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>101
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358870567163456429)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>7
,p_column_id=>wwv_flow_api.id(358870165472456429)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358871228217456431)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>8
,p_column_id=>wwv_flow_api.id(358870756273456429)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358871846528456431)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>9
,p_column_id=>wwv_flow_api.id(358871421920456431)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>195
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358872426487456431)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>10
,p_column_id=>wwv_flow_api.id(358872042065456431)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>205
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358873036169456431)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>15
,p_column_id=>wwv_flow_api.id(358872641222456431)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>170
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358873556808456431)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>13
,p_column_id=>wwv_flow_api.id(358873219337456431)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358874252699456433)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>46
,p_column_id=>wwv_flow_api.id(358873840906456431)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>237
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358874776445456433)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>12
,p_column_id=>wwv_flow_api.id(358874362227456433)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>98
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358875455754456433)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>16
,p_column_id=>wwv_flow_api.id(358875025984456433)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358876026557456434)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>17
,p_column_id=>wwv_flow_api.id(358875653069456434)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358876557823456436)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>18
,p_column_id=>wwv_flow_api.id(358876171875456434)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>100
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358877249374456439)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>18
,p_column_id=>wwv_flow_api.id(358876854956456439)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358877800994456440)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>19
,p_column_id=>wwv_flow_api.id(358877389142456439)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358878412767456443)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>20
,p_column_id=>wwv_flow_api.id(358878013389456442)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358878998150456443)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>21
,p_column_id=>wwv_flow_api.id(358878636372456443)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358879604851456443)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>22
,p_column_id=>wwv_flow_api.id(358879216859456443)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358880256206456443)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>23
,p_column_id=>wwv_flow_api.id(358879847074456443)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358880764460456445)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>24
,p_column_id=>wwv_flow_api.id(358880430537456445)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358881394830456445)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>25
,p_column_id=>wwv_flow_api.id(358880980454456445)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358882004264456445)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>26
,p_column_id=>wwv_flow_api.id(358881602687456445)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358882634015456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>27
,p_column_id=>wwv_flow_api.id(358882215991456445)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358883253749456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>28
,p_column_id=>wwv_flow_api.id(358882757405456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358883814076456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>29
,p_column_id=>wwv_flow_api.id(358883447054456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358884407561456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>30
,p_column_id=>wwv_flow_api.id(358883986084456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358885004699456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>31
,p_column_id=>wwv_flow_api.id(358884627861456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358885630820456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>32
,p_column_id=>wwv_flow_api.id(358885223020456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358886224167456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>33
,p_column_id=>wwv_flow_api.id(358885851167456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358886771071456447)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>34
,p_column_id=>wwv_flow_api.id(358886414397456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358887438429456448)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>35
,p_column_id=>wwv_flow_api.id(358887045115456447)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358888010521456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>36
,p_column_id=>wwv_flow_api.id(358887598732456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358888617625456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>37
,p_column_id=>wwv_flow_api.id(358888246139456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358889172461456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>38
,p_column_id=>wwv_flow_api.id(358888835322456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358889837194456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>39
,p_column_id=>wwv_flow_api.id(358889429490456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358890430359456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>40
,p_column_id=>wwv_flow_api.id(358889965941456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358891042155456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>41
,p_column_id=>wwv_flow_api.id(358890571744456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358891625886456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>42
,p_column_id=>wwv_flow_api.id(358891226723456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358892203121456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>43
,p_column_id=>wwv_flow_api.id(358891801758456450)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358892853838456450)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>51
,p_column_id=>wwv_flow_api.id(358892423556456450)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>119
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358893414621456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>65
,p_column_id=>wwv_flow_api.id(358893054323456450)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>91
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358894001931456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>46
,p_column_id=>wwv_flow_api.id(358893571263456451)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358894558180456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>49
,p_column_id=>wwv_flow_api.id(358894231937456451)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>138
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358895206105456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>48
,p_column_id=>wwv_flow_api.id(358894758088456451)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>165
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358895796488456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>49
,p_column_id=>wwv_flow_api.id(358895414332456451)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358896393794456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>50
,p_column_id=>wwv_flow_api.id(358895969129456451)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358896961730456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>51
,p_column_id=>wwv_flow_api.id(358896595535456451)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358897637193456451)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>52
,p_column_id=>wwv_flow_api.id(358897163217456451)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358898161042456457)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>53
,p_column_id=>wwv_flow_api.id(358897806871456451)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358898758987456461)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>54
,p_column_id=>wwv_flow_api.id(358898414309456457)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358899447291456462)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>55
,p_column_id=>wwv_flow_api.id(358899025508456461)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358899995780456462)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>56
,p_column_id=>wwv_flow_api.id(358899592187456462)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358900599989456462)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>57
,p_column_id=>wwv_flow_api.id(358900184707456462)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358901159019456464)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>58
,p_column_id=>wwv_flow_api.id(358900759637456462)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358901842703456464)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>59
,p_column_id=>wwv_flow_api.id(358901385887456464)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358902364233456464)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>60
,p_column_id=>wwv_flow_api.id(358901986816456464)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358902984111456464)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>61
,p_column_id=>wwv_flow_api.id(358902560563456464)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(358903600458456465)
,p_view_id=>wwv_flow_api.id(358866475418456412)
,p_display_seq=>62
,p_column_id=>wwv_flow_api.id(358903224278456464)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(44998405096230985)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_api.id(126016982942901720)
,p_button_name=>'CREATE'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'BELOW_BOX'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(44998876622230985)
,p_button_sequence=>40
,p_button_plug_id=>wwv_flow_api.id(126016982942901720)
,p_button_name=>'Clear'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Clear'
,p_button_position=>'BELOW_BOX'
,p_button_redirect_url=>'f?p=&APP_ID.:369:&SESSION.::&DEBUG.:RP,294::'
,p_button_condition_type=>'NEVER'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(44999280120230985)
,p_button_sequence=>50
,p_button_plug_id=>wwv_flow_api.id(126016982942901720)
,p_button_name=>'Cancel'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Cancel'
,p_button_position=>'BELOW_BOX'
,p_button_redirect_url=>'f?p=&APP_ID.:368:&SESSION.::&DEBUG.:RP,369::'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(44999599812230985)
,p_button_sequence=>60
,p_button_plug_id=>wwv_flow_api.id(126016982942901720)
,p_button_name=>'Search'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--stretch'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Add'
,p_button_position=>'BELOW_BOX'
,p_button_condition_type=>'NEVER'
,p_button_cattributes=>'style = "width:80px;"'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44815595449970320)
,p_name=>'P369_DOCNUMBR'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_prompt=>'Document No'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44815729812970321)
,p_name=>'P369_DOCTDATE'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_item_default=>'sysdate'
,p_item_default_type=>'EXPRESSION'
,p_item_default_language=>'PLSQL'
,p_prompt=>'Date'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>30
,p_cMaxlength=>4000
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>1
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44815907825970323)
,p_name=>'P369_PREVREF'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_prompt=>'Previous Voucher Reference'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>22
,p_cMaxlength=>4000
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816052389970324)
,p_name=>'P369_REFNUMBR'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_prompt=>'Reference'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>26
,p_cMaxlength=>4000
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816098559970325)
,p_name=>'P369_REFDATE'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_prompt=>'Ref. Date'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>26
,p_cMaxlength=>4000
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816274427970326)
,p_name=>'P369_COSTCODE'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_prompt=>'Cost Code'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT j.costdesc S,j.costcode',
'  FROM syjobmas j',
' WHERE compcode = :COMPCODE',
' and j.COSTCODE in (select CABASECC  from sycstacc',
'where Upper(GRUPCODE) = UPPER(:APP_USER))'))
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816384973970327)
,p_name=>'P369_BANK_CODE'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_api.id(126013353243901684)
,p_prompt=>'Bank Name'
,p_display_as=>'NATIVE_POPUP_LOV'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select LPAD(''SELECT BANK'',50,''#'') b,'''' BANKCODE',
'from DUAL',
'UNION ALL',
'select distinct W.BANKNAME b,W.BANKCODE',
'from ACBNKVW w',
'where W.COMPCODE = :compcode',
''))
,p_lov_display_null=>'YES'
,p_cSize=>40
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_lov_display_extra=>'YES'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'DIALOG'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_04=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816405151970328)
,p_name=>'P369_BANK_BRANCH'
,p_item_sequence=>120
,p_item_plug_id=>wwv_flow_api.id(126013353243901684)
,p_prompt=>'Bank Branch'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>100
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816547941970329)
,p_name=>'P369_CHEQUE_NO'
,p_item_sequence=>140
,p_item_plug_id=>wwv_flow_api.id(126013353243901684)
,p_prompt=>'Cheque No'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>30
,p_colspan=>6
,p_grid_column=>1
,p_grid_label_column_span=>2
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
,p_attribute_02=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(44816646596970330)
,p_name=>'P369_DATE'
,p_item_sequence=>160
,p_item_plug_id=>wwv_flow_api.id(126013353243901684)
,p_prompt=>'Date'
,p_display_as=>'NATIVE_DATE_PICKER'
,p_cSize=>12
,p_begin_on_new_line=>'N'
,p_grid_label_column_span=>1
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_encrypt_session_state_yn=>'N'
,p_attribute_04=>'button'
,p_attribute_05=>'N'
,p_attribute_07=>'NONE'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45001513829230986)
,p_name=>'P369_GRANDDRTOTAL'
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45001989759230986)
,p_name=>'P369_GRANDCRTOTAL'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45002367698230986)
,p_name=>'P369_GRANDCRTOTAL_1'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45002726465230986)
,p_name=>'P369_SL'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
's_sl number;',
'begin',
' select count(*)+1',
'  into s_sl',
'  from actrndtl;',
'  return s_sl;',
'end;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45003100928230986)
,p_name=>'P369_SUBLEDGER'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45003539257230986)
,p_name=>'P369_CURRCODE'
,p_item_sequence=>120
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
' co_curr varchar2(3);',
'Begin',
'    Select nvl(calcrcde,''DHS'') into co_curr from syparmas',
'     where cacmpcde = :compcode;',
'      return co_curr;',
'Exception',
'    When no_data_found then',
'     co_curr := null;',
'     return co_curr;',
'    When too_many_rows then',
'     co_curr := null;',
'     return co_curr;',
'End;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45003930108230986)
,p_name=>'P369_TOTAL'
,p_item_sequence=>130
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
' co_curr varchar2(3);',
'Begin',
'    Select nvl(calcrcde,''DHS'') into co_curr from syparmas',
'     where cacmpcde = :compcode;',
'      return co_curr;',
'Exception',
'    When no_data_found then',
'     co_curr := null;',
'     return co_curr;',
'    When too_many_rows then',
'     co_curr := null;',
'     return co_curr;',
'End;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45004363070230986)
,p_name=>'P369_EXCGRATE'
,p_item_sequence=>140
,p_item_plug_id=>wwv_flow_api.id(232034011140328546)
,p_item_default=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare ',
'      s_exgrte number;',
'    BEGIN',
'      Select CACONVRT INTO  s_exgrte From sycurmas',
'      where  cacurcde in (Select nvl(calcrcde,''DHS'') ',
'                           from syparmas',
'                          where cacmpcde = :compcode) ',
'        and  rownum   =1;',
'        return s_exgrte;',
'  Exception',
'        When no_data_found then',
'         s_exgrte := null;',
'         return s_exgrte;',
'        When too_many_rows then',
'         s_exgrte := null;',
'         return s_exgrte;',
'        When others then',
'         s_exgrte := null;',
'         return s_exgrte;',
'End;'))
,p_item_default_type=>'FUNCTION_BODY'
,p_item_default_language=>'PLSQL'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45005839584230987)
,p_name=>'P369_BANKCASHHEAD'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45006222590230987)
,p_name=>'P369_CRDRCD'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45007019495230987)
,p_name=>'P369_COSTCODE_1'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45007420291230987)
,p_name=>'P369_AMOUNT'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45007824439230987)
,p_name=>'P369_SATFLG'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_api.id(246338707018420165)
,p_item_default=>'N'
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45035948617230994)
,p_name=>'P369_TRANTYPE'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45036320467230995)
,p_name=>'P369_SUBTTYPE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45036736091230995)
,p_name=>'P369_PRDOCTYP'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45037121276230995)
,p_name=>'P369_PRSUBTYP'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45037544777230995)
,p_name=>'P369_NARATION'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45037926221230995)
,p_name=>'P369_TRNTYP'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45038329617230995)
,p_name=>'P369_SUBTYP'
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45038705073230995)
,p_name=>'P369_TRTRNTYP'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45039157494230995)
,p_name=>'P369_TRSUBTYP'
,p_item_sequence=>90
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45039572723230995)
,p_name=>'P369_NARATION_1'
,p_item_sequence=>100
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(45039916806230995)
,p_name=>'P369_SATVAL'
,p_item_sequence=>110
,p_item_plug_id=>wwv_flow_api.id(358865505758456398)
,p_display_as=>'NATIVE_HIDDEN'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45043103883230996)
,p_name=>'set_code_default'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45043647286230996)
,p_event_id=>wwv_flow_api.id(45043103883230996)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_EXECUTE_PLSQL_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'   CURSOR C',
'   IS',
'      SELECT DFLTACCT, DFLTDBCR DBCRCODE, LOCNCODE',
'        FROM sydocmas',
'       WHERE     compcode = :compcode',
'             AND MODLCODE = ''AC''',
'             AND TRANTYPE = :P369_TRNTYP',
'             AND SUBTTYPE = :P369_SUBTYP;',
'',
'   REC   C%ROWTYPE;',
'BEGIN',
'   OPEN C;',
'',
'   FETCH C INTO REC;',
'',
'   CLOSE C;',
'   if  REC.DFLTACCT is not null then',
'   :P369_BANKCASHHEAD := REC.DFLTACCT;',
'   end if;',
'   if  REC.DBCRCODE is not null then',
'   :P369_CRDRCD := REC.DBCRCODE;',
'   end if;',
'',
'   DECLARE',
'      CURSOR c_cost',
'      IS',
'         SELECT J.COSTCODE',
'           FROM nmwhsmas j',
'          WHERE J.COMPCODE = :compcode AND J.WARECODE = rec.LOCNCODE;',
'',
'      costc   c_cost%ROWTYPE;',
'   BEGIN',
'  ',
'      OPEN c_cost;',
'',
'      FETCH c_cost INTO costc;',
'',
'      CLOSE c_cost;',
'      if costc.COSTCODE is not null then',
'      :P369_COSTCODE_1 := costc.COSTCODE;',
'      end if;',
'   END;',
'END;'))
,p_attribute_02=>'P369_TRNTYP,P369_SUBTYP'
,p_attribute_03=>'P369_COSTCODE_1,P369_BANKCASHHEAD,P369_CRDRCD'
,p_attribute_04=>'N'
,p_attribute_05=>'PLSQL'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45044027720230996)
,p_name=>'set_val'
,p_event_sequence=>20
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'COSTCODE'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45044535857230996)
,p_event_id=>wwv_flow_api.id(45044027720230996)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'COSTCODE'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vcost varchar2(100);',
'begin',
' if :P369_COSTCODE_1 is not null then',
'  vcost := :P369_COSTCODE_1;',
' else',
'  vcost := :P369_COSTCODE;',
' end if;',
'  return vcost;',
'end;'))
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45044982410230996)
,p_name=>'set_debit'
,p_event_sequence=>30
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'DEBIT_AMOUNT'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45045458331230996)
,p_event_id=>wwv_flow_api.id(45044982410230996)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DEBIT_AMOUNT'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vcost number;',
'begin',
'  return 0;',
'end;'))
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45045873093230996)
,p_name=>'set_credit'
,p_event_sequence=>40
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'CREDIT_AMOUNT'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45046305592230997)
,p_event_id=>wwv_flow_api.id(45045873093230996)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'CREDIT_AMOUNT'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vcost number;',
'begin',
'  return 0;',
'end;'))
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45046696289230997)
,p_name=>'show_col'
,p_event_sequence=>50
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_condition_element_type=>'ITEM'
,p_condition_element=>'P369_CRDRCD'
,p_triggering_condition_type=>'NOT_NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
,p_display_when_type=>'NEVER'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45047196747230997)
,p_event_id=>wwv_flow_api.id(45046696289230997)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_DISABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DBCRCODE'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45047748898230997)
,p_event_id=>wwv_flow_api.id(45046696289230997)
,p_event_result=>'FALSE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_ENABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DBCRCODE'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45048096122230997)
,p_name=>'sum_total'
,p_event_sequence=>60
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(44998405096230985)
,p_bind_type=>'bind'
,p_bind_event_type=>'click'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45048615092230997)
,p_event_id=>wwv_flow_api.id(45048096122230997)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P369_GRANDDRTOTAL'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'    var sumSAL = 0;  ',
'    var sal = 0;  ',
'    $(''.debit'').each(function() {  ',
'        sal = parseFloat($(this).html());  //parseInt($(this).html());  ',
'        ',
'        if (isNaN(sal)) ',
'            {',
'               sal = 0;  ',
'            }',
'        else',
'            {',
'               sal = parseFloat($(this).html());  //parseInt($(this).html());  ',
'            }',
'        sumSAL = sumSAL + sal;  ',
'    });  ',
'    $s(''P369_GRANDDRTOTAL'',sumSAL); ',
'',
' '))
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45049121094230997)
,p_event_id=>wwv_flow_api.id(45048096122230997)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P369_GRANDCRTOTAL'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'    var sumSAL = 0;  ',
'    var sal = 0;  ',
'    $(''.credit'').each(function() {  ',
'        sal = parseFloat($(this).html());  //parseInt($(this).html());  ',
'         if (isNaN(sal)) ',
'            {',
'               sal=0; ',
'            }',
'         else',
'            {',
'               sal = parseFloat($(this).html());   //parseInt($(this).html());  ',
'            }',
'        sumSAL = sumSAL + sal;  ',
'    });  ',
'    $s(''P369_GRANDCRTOTAL'',sumSAL);  ',
'',
'',
'     '))
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45049646660230997)
,p_event_id=>wwv_flow_api.id(45048096122230997)
,p_event_result=>'TRUE'
,p_action_sequence=>30
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SUBMIT_PAGE'
,p_attribute_02=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45050067498230997)
,p_name=>'check_costcd'
,p_event_sequence=>70
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_triggering_element=>'ACCTCODE'
,p_condition_element_type=>'ITEM'
,p_condition_element=>'P369_COSTCODE'
,p_triggering_condition_type=>'NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
,p_display_when_type=>'NEVER'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45050516166230997)
,p_event_id=>wwv_flow_api.id(45050067498230997)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P369_SATVAL'
,p_attribute_01=>'STATIC_ASSIGNMENT'
,p_attribute_02=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45050982369230997)
,p_name=>'show_mess'
,p_event_sequence=>80
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P369_SATVAL'
,p_condition_element=>'P369_SATVAL'
,p_triggering_condition_type=>'EQUALS'
,p_triggering_expression=>'Y'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45051431727230997)
,p_event_id=>wwv_flow_api.id(45050982369230997)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_ALERT'
,p_attribute_01=>'&#x27;ERROR: Cost center cannot be blank...&#x27;'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45051884683230997)
,p_name=>'set_cs'
,p_event_sequence=>90
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P369_COSTCODE_1'
,p_condition_element=>'P369_COSTCODE_1'
,p_triggering_condition_type=>'NOT_NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45052374040230998)
,p_event_id=>wwv_flow_api.id(45051884683230997)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SET_VALUE'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P369_COSTCODE'
,p_attribute_01=>'FUNCTION_BODY'
,p_attribute_06=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
'  return :P369_COSTCODE_1;',
'end;'))
,p_attribute_07=>'P369_COSTCODE_1'
,p_attribute_08=>'Y'
,p_attribute_09=>'N'
,p_wait_for_result=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45052697844230998)
,p_name=>'CONFIRM'
,p_event_sequence=>100
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P369_SHOW_ALT'
,p_condition_element=>'P369_SHOW_ALT'
,p_triggering_condition_type=>'EQUALS'
,p_triggering_expression=>'Y'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45053226357230998)
,p_event_id=>wwv_flow_api.id(45052697844230998)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_ALERT'
,p_attribute_01=>'ERROR: Debit Credit Amount Mismatch........'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45053639787230998)
,p_name=>'set_credit_disable'
,p_event_sequence=>110
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_triggering_element=>'DEBIT_AMOUNT'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'DEBIT_AMOUNT'
,p_triggering_condition_type=>'GREATER_THAN'
,p_triggering_expression=>'0'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45054132224230998)
,p_event_id=>wwv_flow_api.id(45053639787230998)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_DISABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'CREDIT_AMOUNT'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45054660083230998)
,p_event_id=>wwv_flow_api.id(45053639787230998)
,p_event_result=>'FALSE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_ENABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'CREDIT_AMOUNT'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45055040674230998)
,p_name=>'set_debit_disable'
,p_event_sequence=>120
,p_triggering_element_type=>'COLUMN'
,p_triggering_region_id=>wwv_flow_api.id(358865505758456398)
,p_triggering_element=>'CREDIT_AMOUNT'
,p_condition_element_type=>'COLUMN'
,p_condition_element=>'CREDIT_AMOUNT'
,p_triggering_condition_type=>'GREATER_THAN'
,p_triggering_expression=>'0'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45055507632230998)
,p_event_id=>wwv_flow_api.id(45055040674230998)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_DISABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DEBIT_AMOUNT'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45056001633230998)
,p_event_id=>wwv_flow_api.id(45055040674230998)
,p_event_result=>'FALSE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_ENABLE'
,p_affected_elements_type=>'COLUMN'
,p_affected_elements=>'DEBIT_AMOUNT'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(45056474063230998)
,p_name=>'New'
,p_event_sequence=>130
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(45056901844230998)
,p_event_id=>wwv_flow_api.id(45056474063230998)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_CLEAR'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P369_DOCNUMBR'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45042730896230996)
,p_process_sequence=>100
,p_process_point=>'AFTER_FOOTER'
,p_process_type=>'NATIVE_SESSION_STATE'
,p_process_name=>'set_det'
,p_attribute_01=>'CLEAR_CACHE_FOR_ITEMS'
,p_attribute_03=>'P369_GRANDDRTOTAL,P369_GRANDCRTOTAL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_type=>'NEVER'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45041505737230996)
,p_process_sequence=>40
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'INSERT_OLTERNATE_RECORD'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'BEGIN',
'IF :P369_DOCNUMBR IS NOT NULL THEN',
'insert into actrndtl (COMPCODE,DOCTTYPE,SUBTTYPE,DOCNUMBR,DOCTDATE,SERLNUMB,ACCTCODE,COSTCODE,SUBLEDCD,DBCRCODE,CURRCODE,',
'EXCGRATE,JVFCAMNT,JVLCAMNT,ORGAMTFC,ORGAMTLC,STATCODE,OPRSTAMP,TIMSTAMP)',
'values(:compcode,:P369_TRNTYP,:P369_SUBTYP,:P369_DOCNUMBR,TRUNC(SYSDATE),:P369_SL,:P369_BANKCASHHEAD,:P369_COSTCODE,:P369_SUBLEDGER,',
':P369_CRDRCD,:P369_CURRCODE,:P369_EXCGRATE,:P369_AMOUNT,:P369_AMOUNT,:P369_AMOUNT,:P369_AMOUNT,''N'',:APP_USER,SYSDATE);',
'COMMIT;',
'END IF;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_type=>'NEVER'
,p_process_success_message=>'Transaction No generated successfully..:&P369_DOCNUMBR_1.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45040303572230995)
,p_process_sequence=>80
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_api.id(358865505758456398)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'Journal Entry - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_only_for_changed_rows=>'N'
,p_process_success_message=>'Transaction No generated successfully..:&P369_DOCNUMBR.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45041137926230996)
,p_process_sequence=>20
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'check_amt_validation'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' vtotal number;',
'begin',
'if nvl(to_number(:P369_GRANDDRTOTAL),0) <> nvl(to_number(:P369_GRANDCRTOTAL),0) then',
'raise_application_error(-20001,''Debit Credit amount mismatch...'');',
'end if;',
'end;',
''))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45042365670230996)
,p_process_sequence=>40
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'GEN_DOC'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' DOCNUM varchar2(100);',
'    begin',
'           Docnumber_Generation(:compcode, ''AC'', :P369_TRNTYP,:P369_SUBTYP,trunc(sysdate)  ,'''',''AC'', DOCNUM);',
'        :P369_DOCNUMBR:=DOCNUM;',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_type=>'NEVER'
,p_process_is_stateful_y_n=>'Y'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45040712863230995)
,p_process_sequence=>50
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_region_id=>wwv_flow_api.id(358865505758456398)
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'pre_insert'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
' DOCNUM varchar2(100);',
'begin',
' :P369_DOCNUMBR := :DOCNUMBR;',
' :JVFCAMNT := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);',
' :JVLCAMNT := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);',
' :ORGAMTFC := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);',
' :ORGAMTLC := nvl(:DEBIT_AMOUNT,0) + nvl(:CREDIT_AMOUNT,0);			',
' :SUBLEDCD := :CUSTOMER;',
' :BANKCODE := :P369_BANK_CODE;',
' :BANKBRCH := :P369_BANK_BRANCH;',
' :CHEQUENO := :P369_CHEQUE_NO;',
' :CHEQUEDT := :P369_DATE;',
' if :DEBIT_AMOUNT>0 then',
'  :DBCRCODE:=''D'';',
' end if;',
' if :CREDIT_AMOUNT>0 then',
'  :DBCRCODE:=''C'';',
' end if;',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_success_message=>'Transaction No generated successfully..:&P369_DOCNUMBR.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45041986401230996)
,p_process_sequence=>60
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'post'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
':P369_SATFLG := ''Y'';',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_api.id(44998405096230985)
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(45613033696629446)
,p_process_sequence=>90
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_region_id=>wwv_flow_api.id(358865505758456398)
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'check customer'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'v_rcvflg varchar2(10);',
'begin',
'select a.EMPLRECV',
' into v_rcvflg',
'  FROM sychrtac a',
' WHERE a.compcode = :COMPCODE AND NVL (a.HEADFLAG, ''Y'') = ''N''',
' and A.ACCTCODE = :ACCTCODE;',
' ',
' if v_rcvflg = ''Y'' and :SUBLEDCD is null then',
'  raise_application_error(-20000,''Customer cannot be blank'');',
' end if;',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
wwv_flow_api.component_end;
end;
/
