prompt --application/pages/page_00479
begin
--   Manifest
--     PAGE: 00479
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>479
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>'Finished Good Received  Report '
,p_page_mode=>'MODAL'
,p_step_title=>'&PROGDESC.'
,p_autocomplete_on_off=>'OFF'
,p_step_template=>wwv_flow_api.id(19712461351817939)
,p_page_template_options=>'#DEFAULT#'
,p_dialog_height=>'650'
,p_protection_level=>'C'
,p_last_updated_by=>'MONIR'
,p_last_upd_yyyymmddhh24miss=>'20201103191421'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(55924666985518435)
,p_plug_name=>'Finished Good Received'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(47587389655858184)
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'V_PENDING_FINISHED_GOOD_RCV'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(55925056847518437)
,p_name=>'Report 1'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_max_rows_per_page=>'100'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:480:&SESSION.::&DEBUG.:RP,480:P480_DOCNUMBR,P480_DOCTTYPE,P480_DOCTDATE,P480_APPRVDBY,P480_COSTCODE,P480_CURRCODE,P480_EXCGRATE,P480_PARTYCDE,P480_RAISEDBY,P480_SUBTTYPE,P480_WARECODE:#PORT_RECEIVE_NO#,#DOCTTYPE#,#RECEIVE_DATE#,#APPRVDBY'
||'#,#COSTCODE#,#CURRCODE#,#EXCGRATE#,#PARTYCDE#,#RAISEDBY#,#SUBTTYPE#,#WARECODE##DOCNUMBR#\'
,p_detail_link_text=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil.png" class="apex-edit-pencil" alt="Edit">'
,p_detail_link_auth_scheme=>wwv_flow_api.id(57864979130212531)
,p_owner=>'MONIR'
,p_internal_uid=>55925056847518437
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56431466381374650)
,p_db_column_name=>'COMPCODE'
,p_display_order=>15
,p_column_identifier=>'G'
,p_column_label=>'Compcode'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56660895416859201)
,p_db_column_name=>'PORT_RECEIVE_NO'
,p_display_order=>25
,p_column_identifier=>'H'
,p_column_label=>'Port Receive No'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56660994589859202)
,p_db_column_name=>'RECEIVE_DATE'
,p_display_order=>35
,p_column_identifier=>'I'
,p_column_label=>'Receive Date'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661034934859203)
,p_db_column_name=>'LC_NO'
,p_display_order=>45
,p_column_identifier=>'J'
,p_column_label=>'LC No.'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661122577859204)
,p_db_column_name=>'MANIFEAST_NO'
,p_display_order=>55
,p_column_identifier=>'K'
,p_column_label=>'Manifeast No.'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661248408859205)
,p_db_column_name=>'INVOICE_NO'
,p_display_order=>65
,p_column_identifier=>'L'
,p_column_label=>'Invoice No.'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661300457859206)
,p_db_column_name=>'WARECODE'
,p_display_order=>75
,p_column_identifier=>'M'
,p_column_label=>'Warecode'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661455654859207)
,p_db_column_name=>'WAREHOUSE'
,p_display_order=>85
,p_column_identifier=>'N'
,p_column_label=>'Warehouse'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661596944859208)
,p_db_column_name=>'COSTCODE'
,p_display_order=>95
,p_column_identifier=>'O'
,p_column_label=>'Costcode'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(55926726281518440)
,p_db_column_name=>'PARTYCDE'
,p_display_order=>105
,p_column_identifier=>'E'
,p_column_label=>'Partycde'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661678903859209)
,p_db_column_name=>'PARTYNAME'
,p_display_order=>115
,p_column_identifier=>'P'
,p_column_label=>'Party Name'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661700504859210)
,p_db_column_name=>'CURRCODE'
,p_display_order=>125
,p_column_identifier=>'Q'
,p_column_label=>'Currcode'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56661894973859211)
,p_db_column_name=>'EXCGRATE'
,p_display_order=>135
,p_column_identifier=>'R'
,p_column_label=>'Excgrate'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56662136875859214)
,p_db_column_name=>'SMANCODE'
,p_display_order=>145
,p_column_identifier=>'S'
,p_column_label=>'Smancode'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56662250495859215)
,p_db_column_name=>'REFNUMBR'
,p_display_order=>155
,p_column_identifier=>'T'
,p_column_label=>'Refnumbr'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56662341497859216)
,p_db_column_name=>'REFNDATE'
,p_display_order=>165
,p_column_identifier=>'U'
,p_column_label=>'Refndate'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56662471377859217)
,p_db_column_name=>'MARKPCNT'
,p_display_order=>175
,p_column_identifier=>'V'
,p_column_label=>'Markpcnt'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56662574541859218)
,p_db_column_name=>'REQDDATE'
,p_display_order=>185
,p_column_identifier=>'W'
,p_column_label=>'Reqddate'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56663660043859229)
,p_db_column_name=>'DOCTTYPE'
,p_display_order=>195
,p_column_identifier=>'X'
,p_column_label=>'Docttype'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56663774694859230)
,p_db_column_name=>'SUBTTYPE'
,p_display_order=>205
,p_column_identifier=>'Y'
,p_column_label=>'Subttype'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56663855538859231)
,p_db_column_name=>'RAISEDBY'
,p_display_order=>215
,p_column_identifier=>'Z'
,p_column_label=>'Raisedby'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(56663931399859232)
,p_db_column_name=>'APPRVDBY'
,p_display_order=>225
,p_column_identifier=>'AA'
,p_column_label=>'Apprvdby'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(55946455965541675)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'559465'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'PORT_RECEIVE_NO:RECEIVE_DATE:LC_NO:MANIFEAST_NO:INVOICE_NO:WAREHOUSE:PARTYNAME::SMANCODE:REFNUMBR:REFNDATE:MARKPCNT:REQDDATE:DOCTTYPE:SUBTTYPE:RAISEDBY:APPRVDBY'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(55928507825518443)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_api.id(55924666985518435)
,p_button_name=>'CANCEL'
,p_button_static_id=>'CANCEL'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#:t-Button--iconRight'
,p_button_template_id=>wwv_flow_api.id(47630535519858357)
,p_button_image_alt=>'Cancel'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_warn_on_unsaved_changes=>null
,p_button_css_classes=>'CANCEL'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(55927554496518443)
,p_name=>'Edit Report - Dialog Closed'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_api.id(55924666985518435)
,p_bind_type=>'bind'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(55928036698518443)
,p_event_id=>wwv_flow_api.id(55927554496518443)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(55924666985518435)
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(52510113829644613)
,p_name=>'Close Dialog'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(55928507825518443)
,p_bind_type=>'bind'
,p_bind_event_type=>'click'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(52510290992644614)
,p_event_id=>wwv_flow_api.id(52510113829644613)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_DIALOG_CLOSE'
);
wwv_flow_api.component_end;
end;
/
