prompt --application/pages/page_00244
begin
--   Manifest
--     PAGE: 00244
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>244
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>'Service Charge Master'
,p_page_mode=>'MODAL'
,p_step_title=>'Service Charge Master'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_last_updated_by=>'RILADM'
,p_last_upd_yyyymmddhh24miss=>'20171012111138'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(136098830655171393)
,p_plug_name=>'Service Charge Master'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(47587389655858184)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Select ROWID rwid,SRVCNOPK, COMPCODE, RATEDATE, TIMSTAMP, ',
'ACTIVFLG, SRVCCODE, SRVCNAME, SRVMASCD, VHLMASCD, ',
'GRPMASCD, SJOBRATE, SREQTIME, RAISEDBY, APPRVDBY, ',
'APPRDATE, REMARKSS, LBORCHRG, ',
'SREQDAYS, MODELCDE, MODCRGAM, MODDISAM, ',
'CRGPRCNT, MODIFYDT, LABORGRP, COMMGRUP from nmcrgmas'))
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(136098911392171393)
,p_name=>'Service Charge Master'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:245:&SESSION.::&DEBUG.::P245_ROWID:#RWID#'
,p_detail_link_text=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil.png" class="apex-edit-pencil" alt="Edit">'
,p_icon_view_columns_per_row=>1
,p_owner=>'RILADM'
,p_internal_uid=>98944044266490899
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136099269783171396)
,p_db_column_name=>'RWID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Rwid'
,p_allow_sorting=>'N'
,p_allow_filtering=>'N'
,p_allow_highlighting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'OTHER'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_rpt_show_filter_lov=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136099669403171402)
,p_db_column_name=>'SRVCNOPK'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Srvcnopk'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136100136817171402)
,p_db_column_name=>'COMPCODE'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Compcode'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136100533643171402)
,p_db_column_name=>'RATEDATE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Ratedate'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136100952745171402)
,p_db_column_name=>'TIMSTAMP'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Timstamp'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136101290884171404)
,p_db_column_name=>'ACTIVFLG'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Activ Flg'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136101685275171404)
,p_db_column_name=>'SRVCCODE'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Service Code'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136102110330171406)
,p_db_column_name=>'SRVCNAME'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Service Name'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136102554742171406)
,p_db_column_name=>'SRVMASCD'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Service System'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136102930935171406)
,p_db_column_name=>'VHLMASCD'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Vhlmascd'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136103345074171407)
,p_db_column_name=>'GRPMASCD'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Grpmascd'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136103758298171407)
,p_db_column_name=>'SJOBRATE'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Sjobrate'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136104087756171407)
,p_db_column_name=>'SREQTIME'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Sreqtime'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136104502472171407)
,p_db_column_name=>'RAISEDBY'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Raisedby'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136104871960171409)
,p_db_column_name=>'APPRVDBY'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Apprvdby'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136105330431171409)
,p_db_column_name=>'APPRDATE'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Apprdate'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136105756177171409)
,p_db_column_name=>'REMARKSS'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Remarks'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136106133893171409)
,p_db_column_name=>'LBORCHRG'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Lborchrg'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136106518444171409)
,p_db_column_name=>'SREQDAYS'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Sreqdays'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136106959897171410)
,p_db_column_name=>'MODELCDE'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Modelcde'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136107301787171410)
,p_db_column_name=>'MODCRGAM'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Modcrgam'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136107692849171410)
,p_db_column_name=>'MODDISAM'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Moddisam'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136108088102171412)
,p_db_column_name=>'CRGPRCNT'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Crgprcnt'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136108496345171412)
,p_db_column_name=>'MODIFYDT'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Modifydt'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136108953678171412)
,p_db_column_name=>'LABORGRP'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Laborgrp'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(136109366667171412)
,p_db_column_name=>'COMMGRUP'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Commgrup'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(136146294552199871)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'989915'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'SRVCCODE:SRVCNAME:SRVMASCD:REMARKSS:ACTIVFLG:'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(136155638927229859)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(136098830655171393)
,p_button_name=>'SERVICE_CHARGE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Add Service Charge'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:245:&SESSION.::&DEBUG.:245::'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(38238544830691706)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_api.id(136098830655171393)
,p_button_name=>'CANCEL'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Cancel'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:1:&SESSION.::&DEBUG.:::'
);
wwv_flow_api.component_end;
end;
/
