prompt --application/pages/page_00162
begin
--   Manifest
--     PAGE: 00162
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>162
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>' Buyer Yearly Information'
,p_page_mode=>'MODAL'
,p_step_title=>' Buyer Yearly Information'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_help_text=>'No help is available for this page.'
,p_last_updated_by=>'RILADM'
,p_last_upd_yyyymmddhh24miss=>'20161006140737'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(95274236304448686)
,p_plug_name=>' Buyer Yearly Information'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(47587389655858184)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT ACNTNAME, APPRDATE, APPRQNTY,BANKNAME, BATCHNUM, ',
'BODY_TYPE, BRANCHNM, COLORCDE, COMMCODE, COMPCODE, ',
'COSTCODE, COSTRATE, CURRCODE, CUSTMRID, DELVCOND, ',
'DELYDATE, DISCAMNT, DISCPCNT, DISCTAMT, DOCNUMBR, ',
'DOCTDATE, DOWN_PAYMENT, DWDOCDTE, DWDOCNUM,',
'FREE_REGSTRATION,HUOMCODE, INSTALLMENT_PAY, INTEREST_AMOUNT, ',
'ITEMCODE, ITEMDESC, ITEMLONG, ITEMRATE,LOAN_AMOUNT,',
'LUOMCODE, LUOMDESC,MONTHLY_INSTALLMENT, MSFCAMNT, ',
'MSLCAMNT, NO_OF_INSTALLMENT, OFRLETTER, OPRSTAMP,',
'ORGNQNTY,PAMTMODE, PARTYCDE,POSIBLE_INST_END_DATE, POSIBLE_INST_START_DATE,',
'PRODUCTION_COMPLETE_QTY, RAISEDBY, REFNDATE, REFNUMBR, REG_PLACE,',
' REG_TYPE, REGNUMBR, REMARKSS, REQDDATE, SALERATE,',
' SALES_TYPE,SLSOFRNO, SMANCODE, SOFNUMBR,STATUSCD,TRNSQNTY, UPDOCDTE, UPDOCNUM, UPDOCSRL, UPDOCTYP,WARECODE, WHSZONPK, ZONLCODE,',
'(select NMCODDES from nmcodmas ',
'       where compcode=a.compcode',
'       and NMHRDCDE=''CLR''',
'       and NMSOFCDE=a.COLORCDE)COLORCDE_NAME,',
'      (select CUSTNAME from nmcusmas ',
'       where compcode=a.compcode',
'       and CUSTMRID=a.CUSTMRID ) CUSTMRID_NAME,',
'       (select SMANNAME from nmsmnmas ',
'       where compcode=a.compcode',
'       and SMANCODE=a.SMANCODE',
'       and COSTCODE=a.COSTCODE) SMANCODE_NAME,',
'       (select WAREDESC from nmwhsmas ',
'       where compcode=a.compcode',
'       and WARECODE=a.WARECODE ) WARECODE_NAME',
'             from nmslsofr a',
'       where compcode=:compcode',
'       ',
'        AND trunc(DOCTDATE) BETWEEN ADD_MONTHS (TRUNC (ADD_MONTHS (SYSDATE, 6), ''YEAR''),',
'                                    -6',
'                                   )',
'                    AND   ADD_MONTHS (TRUNC (ADD_MONTHS (SYSDATE, 6), ''YEAR''),',
'                                      6',
'                                     )',
'                        - 1 '))
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(95274649217448686)
,p_name=>' Buyer Daily Information'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'BOTTOM_LEFT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link_text=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil.png" class="apex-edit-pencil" alt="Edit">'
,p_icon_view_columns_per_row=>1
,p_owner=>'RILADM'
,p_internal_uid=>58119782091768192
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95274725094448686)
,p_db_column_name=>'ACNTNAME'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Acntname'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95285539517448694)
,p_db_column_name=>'APPRDATE'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Apprdate'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95292740343448699)
,p_db_column_name=>'APPRQNTY'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Apprqnty'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95293131884448699)
,p_db_column_name=>'BANKNAME'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Bankname'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95293512831448699)
,p_db_column_name=>'BATCHNUM'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Batchnum'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95293869579448699)
,p_db_column_name=>'BODY_TYPE'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Body Type'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95294268855448699)
,p_db_column_name=>'BRANCHNM'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Branchnm'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95294762669448699)
,p_db_column_name=>'COLORCDE'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Colorcde'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95295150144448699)
,p_db_column_name=>'COMMCODE'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Commcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95295537783448699)
,p_db_column_name=>'COMPCODE'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Compcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95295938754448700)
,p_db_column_name=>'COSTCODE'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Costcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95296359037448700)
,p_db_column_name=>'COSTRATE'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Costrate'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95296717609448700)
,p_db_column_name=>'CURRCODE'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Currcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95297103647448700)
,p_db_column_name=>'CUSTMRID'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Custmrid'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95297481020448700)
,p_db_column_name=>'DELVCOND'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Delvcond'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95297905414448700)
,p_db_column_name=>'DELYDATE'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Delydate'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95298282375448700)
,p_db_column_name=>'DISCAMNT'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Discamnt'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95298743065448700)
,p_db_column_name=>'DISCPCNT'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Discpcnt'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95299108301448700)
,p_db_column_name=>'DISCTAMT'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Disctamt'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95299565376448700)
,p_db_column_name=>'DOCNUMBR'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Document No.'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95299878581448700)
,p_db_column_name=>'DOCTDATE'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Date'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95300364875448700)
,p_db_column_name=>'DOWN_PAYMENT'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Down Payment'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95300744673448700)
,p_db_column_name=>'DWDOCDTE'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Dwdocdte'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95301098239448702)
,p_db_column_name=>'DWDOCNUM'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Dwdocnum'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95301512578448702)
,p_db_column_name=>'FREE_REGSTRATION'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Free Registration'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95301921219448702)
,p_db_column_name=>'HUOMCODE'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Huomcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95275089592448686)
,p_db_column_name=>'INSTALLMENT_PAY'
,p_display_order=>27
,p_column_identifier=>'AA'
,p_column_label=>'Installment Pay'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95275556760448686)
,p_db_column_name=>'INTEREST_AMOUNT'
,p_display_order=>28
,p_column_identifier=>'AB'
,p_column_label=>'Interest Amount'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95275932595448686)
,p_db_column_name=>'ITEMCODE'
,p_display_order=>29
,p_column_identifier=>'AC'
,p_column_label=>'Itemcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95276308520448691)
,p_db_column_name=>'ITEMDESC'
,p_display_order=>30
,p_column_identifier=>'AD'
,p_column_label=>'Item Description'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95276738880448691)
,p_db_column_name=>'ITEMLONG'
,p_display_order=>31
,p_column_identifier=>'AE'
,p_column_label=>'Itemlong'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95277076369448691)
,p_db_column_name=>'ITEMRATE'
,p_display_order=>32
,p_column_identifier=>'AF'
,p_column_label=>'Itemrate'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95277469228448691)
,p_db_column_name=>'LOAN_AMOUNT'
,p_display_order=>33
,p_column_identifier=>'AG'
,p_column_label=>'Loan Amount'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95277925452448691)
,p_db_column_name=>'LUOMCODE'
,p_display_order=>34
,p_column_identifier=>'AH'
,p_column_label=>'Luomcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95278363311448691)
,p_db_column_name=>'LUOMDESC'
,p_display_order=>35
,p_column_identifier=>'AI'
,p_column_label=>'Luomdesc'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95278710421448691)
,p_db_column_name=>'MONTHLY_INSTALLMENT'
,p_display_order=>36
,p_column_identifier=>'AJ'
,p_column_label=>'Monthly Installment'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95279077858448691)
,p_db_column_name=>'MSFCAMNT'
,p_display_order=>37
,p_column_identifier=>'AK'
,p_column_label=>'Msfcamnt'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95279475277448691)
,p_db_column_name=>'MSLCAMNT'
,p_display_order=>38
,p_column_identifier=>'AL'
,p_column_label=>'Total Amount'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95279899037448692)
,p_db_column_name=>'NO_OF_INSTALLMENT'
,p_display_order=>39
,p_column_identifier=>'AM'
,p_column_label=>'No Of Installment'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95280268077448692)
,p_db_column_name=>'OFRLETTER'
,p_display_order=>40
,p_column_identifier=>'AN'
,p_column_label=>'Ofrletter'
,p_allow_sorting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'CLOB'
,p_tz_dependent=>'N'
,p_rpt_show_filter_lov=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95280703085448692)
,p_db_column_name=>'OPRSTAMP'
,p_display_order=>41
,p_column_identifier=>'AO'
,p_column_label=>'Oprstamp'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95281133556448692)
,p_db_column_name=>'ORGNQNTY'
,p_display_order=>42
,p_column_identifier=>'AP'
,p_column_label=>'Orgnqnty'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95281531005448692)
,p_db_column_name=>'PAMTMODE'
,p_display_order=>43
,p_column_identifier=>'AQ'
,p_column_label=>'Pamtmode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95281908806448692)
,p_db_column_name=>'PARTYCDE'
,p_display_order=>44
,p_column_identifier=>'AR'
,p_column_label=>'Partycde'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95282277125448694)
,p_db_column_name=>'POSIBLE_INST_END_DATE'
,p_display_order=>45
,p_column_identifier=>'AS'
,p_column_label=>'Posible Inst End Date'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95282730623448694)
,p_db_column_name=>'POSIBLE_INST_START_DATE'
,p_display_order=>46
,p_column_identifier=>'AT'
,p_column_label=>'Posible Inst Start Date'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95283103275448694)
,p_db_column_name=>'PRODUCTION_COMPLETE_QTY'
,p_display_order=>47
,p_column_identifier=>'AU'
,p_column_label=>'Production Complete Qty'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95283508509448694)
,p_db_column_name=>'RAISEDBY'
,p_display_order=>48
,p_column_identifier=>'AV'
,p_column_label=>'Raisedby'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95283942449448694)
,p_db_column_name=>'REFNDATE'
,p_display_order=>49
,p_column_identifier=>'AW'
,p_column_label=>'Refndate'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95284319864448694)
,p_db_column_name=>'REFNUMBR'
,p_display_order=>50
,p_column_identifier=>'AX'
,p_column_label=>'Refnumbr'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95284711908448694)
,p_db_column_name=>'REG_PLACE'
,p_display_order=>51
,p_column_identifier=>'AY'
,p_column_label=>'Reg Place'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95285085079448694)
,p_db_column_name=>'REG_TYPE'
,p_display_order=>52
,p_column_identifier=>'AZ'
,p_column_label=>'Reg Type'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95285949226448694)
,p_db_column_name=>'REGNUMBR'
,p_display_order=>53
,p_column_identifier=>'BA'
,p_column_label=>'Regnumbr'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95286275623448694)
,p_db_column_name=>'REMARKSS'
,p_display_order=>54
,p_column_identifier=>'BB'
,p_column_label=>'Remarkss'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95286720741448694)
,p_db_column_name=>'REQDDATE'
,p_display_order=>55
,p_column_identifier=>'BC'
,p_column_label=>'Reqddate'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95287159168448695)
,p_db_column_name=>'SALERATE'
,p_display_order=>56
,p_column_identifier=>'BD'
,p_column_label=>'Salerate'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95287559256448695)
,p_db_column_name=>'SALES_TYPE'
,p_display_order=>57
,p_column_identifier=>'BE'
,p_column_label=>'Sales Type'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95287957074448695)
,p_db_column_name=>'SLSOFRNO'
,p_display_order=>58
,p_column_identifier=>'BF'
,p_column_label=>'Slsofrno'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95288314523448695)
,p_db_column_name=>'SMANCODE'
,p_display_order=>59
,p_column_identifier=>'BG'
,p_column_label=>'Smancode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95288709770448695)
,p_db_column_name=>'SOFNUMBR'
,p_display_order=>60
,p_column_identifier=>'BH'
,p_column_label=>'Sofnumbr'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95289068766448695)
,p_db_column_name=>'STATUSCD'
,p_display_order=>61
,p_column_identifier=>'BI'
,p_column_label=>'Statuscd'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95289482503448695)
,p_db_column_name=>'TRNSQNTY'
,p_display_order=>62
,p_column_identifier=>'BJ'
,p_column_label=>'Trnsqnty'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95289870780448695)
,p_db_column_name=>'UPDOCDTE'
,p_display_order=>63
,p_column_identifier=>'BK'
,p_column_label=>'Updocdte'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95290333697448695)
,p_db_column_name=>'UPDOCNUM'
,p_display_order=>64
,p_column_identifier=>'BL'
,p_column_label=>'Updocnum'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95290742295448695)
,p_db_column_name=>'UPDOCSRL'
,p_display_order=>65
,p_column_identifier=>'BM'
,p_column_label=>'Updocsrl'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95291072798448699)
,p_db_column_name=>'UPDOCTYP'
,p_display_order=>66
,p_column_identifier=>'BN'
,p_column_label=>'Updoctyp'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95291539728448699)
,p_db_column_name=>'WARECODE'
,p_display_order=>67
,p_column_identifier=>'BO'
,p_column_label=>'Warecode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95291908799448699)
,p_db_column_name=>'WHSZONPK'
,p_display_order=>68
,p_column_identifier=>'BP'
,p_column_label=>'Whszonpk'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95292273650448699)
,p_db_column_name=>'ZONLCODE'
,p_display_order=>69
,p_column_identifier=>'BQ'
,p_column_label=>'Zonlcode'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95864764364175988)
,p_db_column_name=>'COLORCDE_NAME'
,p_display_order=>70
,p_column_identifier=>'BR'
,p_column_label=>'Color Name'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95865419115175988)
,p_db_column_name=>'CUSTMRID_NAME'
,p_display_order=>71
,p_column_identifier=>'BS'
,p_column_label=>'Customer Name'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95866074104175988)
,p_db_column_name=>'SMANCODE_NAME'
,p_display_order=>72
,p_column_identifier=>'BT'
,p_column_label=>'Salesman Name'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(95866863099175990)
,p_db_column_name=>'WARECODE_NAME'
,p_display_order=>73
,p_column_identifier=>'BU'
,p_column_label=>'Cost Center'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(95302315578448702)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'581475'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'DOCNUMBR:DOCTDATE:CUSTMRID_NAME:SMANCODE_NAME:WARECODE_NAME:ITEMCODE:ITEMDESC:COLORCDE_NAME:SALERATE:DOWN_PAYMENT:LOAN_AMOUNT:NO_OF_INSTALLMENT:MONTHLY_INSTALLMENT:INSTALLMENT_PAY:FREE_REGSTRATION:INTEREST_AMOUNT:MSLCAMNT:'
);
wwv_flow_api.component_end;
end;
/
