prompt --application/pages/page_05003
begin
--   Manifest
--     PAGE: 05003
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>100250
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>5003
,p_user_interface_id=>wwv_flow_api.id(1581890319240888879)
,p_name=>'Update '
,p_page_mode=>'NON_MODAL'
,p_step_title=>'Update '
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_javascript_code=>'var htmldb_delete_message=''"DELETE_CONFIRM_MSG"'';'
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'#navbar {',
'    display: none !important;',
'    overflow: hidden;',
'    position: absolute;',
'    top: 16px;',
'    right: 10px;',
'    font: normal 11px/12px Arial, sans-serif;',
'    color: #000;',
'    text-shadow: 0 1px 0px rgba(255,255,255,.5);',
'}',
'',
'#header {',
'    height: 0px !important;',
'    overflow: hidden;',
'    width: 100%;',
'}',
'',
'#logo {',
'    display: block;',
'    position: static !important;',
'    top: 16px;',
'    left: 10px;',
'}'))
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_last_updated_by=>'SYSADM'
,p_last_upd_yyyymmddhh24miss=>'20170731110147'
);
wwv_flow_api.create_report_region(
 p_id=>wwv_flow_api.id(123484501637715061)
,p_name=>'Followup'
,p_template=>wwv_flow_api.id(47587389655858184)
,p_display_sequence=>15
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#:t-Report--altRowsDefault:t-Report--rowHighlight'
,p_source_type=>'NATIVE_TABFORM'
,p_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select ',
'"ROWID",',
'"COMPCODE",',
'"DOCTTYPE",',
'"SUBTTYPE",',
'"DOCNUMBR",',
'"DOCTDATE",',
'"SERLNUMB",',
'"PARTYCDE",',
'"CUSTMRID",',
'"SMANCODE",',
'"RAISEDBY",',
'"APPRVDBY",',
'"APPRDATE",',
'"ITEMCODE",',
'"WARECODE",',
'"COSTCODE",',
'"REFNUMBR",',
'"REFNDATE",',
'"UPDOCTYP",',
'"UPSUBTYP",',
'"UPDOCNUM",',
'"UPDOCDTE",',
'"UPDOCSRL",',
'"VOC",',
'"REMARKSS",',
'"PRNTFLAG",',
'"STATUSCD",',
'"COMPLETE",',
'"FOLLOWDT",',
'"ENDDDATE",',
'"NEXTDATE",',
'"RMNDTYPE",',
'"FSTRMNDT",',
'"FSTRMTYP",',
'"SNDRMNDT",',
'"SNDRMTYP",',
'"TRDRMNDT",',
'"TRDRMTYP",',
'"OPRSTAMP",',
'"TIMSTAMP",',
'"NMCUSTYP"',
'from "#OWNER#"."NM_MRK_SCH_FOLLOWUP"',
'where DOCNUMBR=:P5003_DOCNUMBR',
''))
,p_ajax_items_to_submit=>'P5003_DOCNUMBR'
,p_lazy_loading=>false
,p_query_row_template=>wwv_flow_api.id(47606600251858234)
,p_query_num_rows=>10
,p_query_options=>'DERIVED_REPORT_COLUMNS'
,p_query_show_nulls_as=>'(null)'
,p_query_break_cols=>'0'
,p_query_no_data_found=>'No data found.'
,p_query_num_rows_type=>'ROW_RANGES_IN_SELECT_LIST'
,p_query_row_count_max=>500
,p_pagination_display_position=>'BOTTOM_RIGHT'
,p_break_type_flag=>'DEFAULT_BREAK_FORMATTING'
,p_csv_output=>'N'
,p_plug_query_strip_html=>'Y'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123562485451715156)
,p_query_column_id=>1
,p_column_alias=>'CHECK$01'
,p_column_display_sequence=>2
,p_column_heading=>'Select Row'
,p_hidden_column=>'Y'
,p_display_as=>'CHECKBOX'
,p_derived_column=>'Y'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123485265851715083)
,p_query_column_id=>2
,p_column_alias=>'ROWID'
,p_column_display_sequence=>3
,p_column_heading=>'Rowid'
,p_hidden_column=>'Y'
,p_display_as=>'WITHOUT_MODIFICATION'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'ROWID'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123485627654715090)
,p_query_column_id=>3
,p_column_alias=>'COMPCODE'
,p_column_display_sequence=>1
,p_column_heading=>'Compcode'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'COMPCODE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123486060738715090)
,p_query_column_id=>4
,p_column_alias=>'DOCTTYPE'
,p_column_display_sequence=>4
,p_column_heading=>'Docttype'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'DOCTTYPE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123486387990715090)
,p_query_column_id=>5
,p_column_alias=>'SUBTTYPE'
,p_column_display_sequence=>5
,p_column_heading=>'Subttype'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'SUBTTYPE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123486780385715090)
,p_query_column_id=>6
,p_column_alias=>'DOCNUMBR'
,p_column_display_sequence=>6
,p_column_heading=>'Docnumbr'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'DOCNUMBR'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123487206163715090)
,p_query_column_id=>7
,p_column_alias=>'DOCTDATE'
,p_column_display_sequence=>7
,p_column_heading=>'Doctdate'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'DOCTDATE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123487595296715090)
,p_query_column_id=>8
,p_column_alias=>'SERLNUMB'
,p_column_display_sequence=>8
,p_column_heading=>'Serlnumb'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'SERLNUMB'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123488043267715092)
,p_query_column_id=>9
,p_column_alias=>'PARTYCDE'
,p_column_display_sequence=>9
,p_column_heading=>'Partycde'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'PARTYCDE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123488425498715092)
,p_query_column_id=>10
,p_column_alias=>'CUSTMRID'
,p_column_display_sequence=>10
,p_column_heading=>'Custmrid'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'CUSTMRID'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123488789066715092)
,p_query_column_id=>11
,p_column_alias=>'SMANCODE'
,p_column_display_sequence=>11
,p_column_heading=>'Smancode'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'SMANCODE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123489195023715094)
,p_query_column_id=>12
,p_column_alias=>'RAISEDBY'
,p_column_display_sequence=>12
,p_column_heading=>'Raisedby'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'RAISEDBY'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123489595936715097)
,p_query_column_id=>13
,p_column_alias=>'APPRVDBY'
,p_column_display_sequence=>13
,p_column_heading=>'Apprvdby'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'APPRVDBY'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123489971134715097)
,p_query_column_id=>14
,p_column_alias=>'APPRDATE'
,p_column_display_sequence=>14
,p_column_heading=>'Apprdate'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'APPRDATE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123490444186715097)
,p_query_column_id=>15
,p_column_alias=>'ITEMCODE'
,p_column_display_sequence=>15
,p_column_heading=>'Itemcode'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'ITEMCODE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123490779941715097)
,p_query_column_id=>16
,p_column_alias=>'WARECODE'
,p_column_display_sequence=>16
,p_column_heading=>'Warecode'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'WARECODE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123491212623715097)
,p_query_column_id=>17
,p_column_alias=>'COSTCODE'
,p_column_display_sequence=>17
,p_column_heading=>'Costcode'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'COSTCODE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123491589946715098)
,p_query_column_id=>18
,p_column_alias=>'REFNUMBR'
,p_column_display_sequence=>18
,p_column_heading=>'Refnumbr'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'REFNUMBR'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123491983757715098)
,p_query_column_id=>19
,p_column_alias=>'REFNDATE'
,p_column_display_sequence=>19
,p_column_heading=>'Refndate'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'REFNDATE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123492432903715098)
,p_query_column_id=>20
,p_column_alias=>'UPDOCTYP'
,p_column_display_sequence=>20
,p_column_heading=>'Updoctyp'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'UPDOCTYP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123492784849715098)
,p_query_column_id=>21
,p_column_alias=>'UPSUBTYP'
,p_column_display_sequence=>21
,p_column_heading=>'Upsubtyp'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'UPSUBTYP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123493257629715098)
,p_query_column_id=>22
,p_column_alias=>'UPDOCNUM'
,p_column_display_sequence=>22
,p_column_heading=>'Updocnum'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'UPDOCNUM'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123493649902715098)
,p_query_column_id=>23
,p_column_alias=>'UPDOCDTE'
,p_column_display_sequence=>23
,p_column_heading=>'Updocdte'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'UPDOCDTE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123494009423715098)
,p_query_column_id=>24
,p_column_alias=>'UPDOCSRL'
,p_column_display_sequence=>24
,p_column_heading=>'Updocsrl'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'UPDOCSRL'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123494466144715098)
,p_query_column_id=>25
,p_column_alias=>'VOC'
,p_column_display_sequence=>25
,p_column_heading=>'Voc'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'VOC'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123494778665715098)
,p_query_column_id=>26
,p_column_alias=>'REMARKSS'
,p_column_display_sequence=>31
,p_column_heading=>'Description'
,p_use_as_row_header=>'N'
,p_display_as=>'TEXTAREA'
,p_lov_show_nulls=>'YES'
,p_column_width=>60
,p_column_height=>1
,p_lov_display_extra=>'YES'
,p_include_in_export=>'Y'
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'REMARKSS'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123495190058715098)
,p_query_column_id=>27
,p_column_alias=>'PRNTFLAG'
,p_column_display_sequence=>26
,p_column_heading=>'Prntflag'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'PRNTFLAG'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123495569713715098)
,p_query_column_id=>28
,p_column_alias=>'STATUSCD'
,p_column_display_sequence=>27
,p_column_heading=>'Statuscd'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'STATUSCD'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123496055277715100)
,p_query_column_id=>29
,p_column_alias=>'COMPLETE'
,p_column_display_sequence=>28
,p_column_heading=>'Complete'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'COMPLETE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123496425025715100)
,p_query_column_id=>30
,p_column_alias=>'FOLLOWDT'
,p_column_display_sequence=>29
,p_column_heading=>'Shedule Date'
,p_use_as_row_header=>'N'
,p_display_as=>'PICK_DATE_DD_MON_YYYY'
,p_lov_show_nulls=>'YES'
,p_column_width=>12
,p_lov_display_extra=>'YES'
,p_include_in_export=>'Y'
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'FOLLOWDT'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123496791460715100)
,p_query_column_id=>31
,p_column_alias=>'ENDDDATE'
,p_column_display_sequence=>30
,p_column_heading=>'Endddate'
,p_use_as_row_header=>'N'
,p_heading_alignment=>'LEFT'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_lov_show_nulls=>'YES'
,p_column_width=>12
,p_lov_display_extra=>'YES'
,p_include_in_export=>'Y'
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'ENDDDATE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123497210282715100)
,p_query_column_id=>32
,p_column_alias=>'NEXTDATE'
,p_column_display_sequence=>35
,p_column_heading=>'Next Shedule Date'
,p_use_as_row_header=>'N'
,p_column_alignment=>'CENTER'
,p_heading_alignment=>'LEFT'
,p_display_as=>'DATE_PICKER'
,p_lov_show_nulls=>'YES'
,p_column_width=>12
,p_lov_display_extra=>'YES'
,p_include_in_export=>'Y'
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'NEXTDATE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123497664682715100)
,p_query_column_id=>33
,p_column_alias=>'RMNDTYPE'
,p_column_display_sequence=>33
,p_column_heading=>'Rmndtype'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'RMNDTYPE'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123498010953715100)
,p_query_column_id=>34
,p_column_alias=>'FSTRMNDT'
,p_column_display_sequence=>34
,p_column_heading=>'Fstrmndt'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'FSTRMNDT'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123498394209715100)
,p_query_column_id=>35
,p_column_alias=>'FSTRMTYP'
,p_column_display_sequence=>36
,p_column_heading=>'Fstrmtyp'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'FSTRMTYP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123498795832715100)
,p_query_column_id=>36
,p_column_alias=>'SNDRMNDT'
,p_column_display_sequence=>37
,p_column_heading=>'Sndrmndt'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'SNDRMNDT'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123499238561715100)
,p_query_column_id=>37
,p_column_alias=>'SNDRMTYP'
,p_column_display_sequence=>38
,p_column_heading=>'Sndrmtyp'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'SNDRMTYP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123499660457715100)
,p_query_column_id=>38
,p_column_alias=>'TRDRMNDT'
,p_column_display_sequence=>39
,p_column_heading=>'Trdrmndt'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'TRDRMNDT'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123500025900715100)
,p_query_column_id=>39
,p_column_alias=>'TRDRMTYP'
,p_column_display_sequence=>41
,p_column_heading=>'Trdrmtyp'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>16
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'TRDRMTYP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123509176555715106)
,p_query_column_id=>40
,p_column_alias=>'OPRSTAMP'
,p_column_display_sequence=>40
,p_column_heading=>'Oprstamp'
,p_hidden_column=>'Y'
,p_display_as=>'TEXT'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'OPRSTAMP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(123509572618715106)
,p_query_column_id=>41
,p_column_alias=>'TIMSTAMP'
,p_column_display_sequence=>42
,p_column_heading=>'Timstamp'
,p_hidden_column=>'Y'
,p_display_as=>'DATE_PICKER'
,p_column_width=>12
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'TIMSTAMP'
);
wwv_flow_api.create_report_columns(
 p_id=>wwv_flow_api.id(124636360811082854)
,p_query_column_id=>42
,p_column_alias=>'NMCUSTYP'
,p_column_display_sequence=>32
,p_column_heading=>'Mode of Customer'
,p_use_as_row_header=>'N'
,p_display_as=>'SELECT_LIST'
,p_inline_lov=>'STATIC:Warm;W,Hot;H,Cold;C'
,p_lov_show_nulls=>'YES'
,p_cattributes=>'style="width: 100%;"'
,p_lov_display_extra=>'YES'
,p_include_in_export=>'Y'
,p_ref_schema=>'ORBRGS'
,p_ref_table_name=>'NM_MRK_SCH_FOLLOWUP'
,p_ref_column_name=>'NMCUSTYP'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(123528767926715125)
,p_button_sequence=>40
,p_button_plug_id=>wwv_flow_api.id(123484501637715061)
,p_button_name=>'ADD'
,p_button_action=>'REDIRECT_URL'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_image_alt=>'Add Row'
,p_button_position=>'BOTTOM'
,p_button_redirect_url=>'javascript:apex.widget.tabular.addRow();'
,p_button_execute_validations=>'N'
,p_button_condition_type=>'NEVER'
,p_grid_new_row=>'N'
,p_grid_new_column=>'N'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(123528665166715125)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_api.id(123484501637715061)
,p_button_name=>'SUBMIT'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_image_alt=>'Apply Changes'
,p_button_position=>'CHANGE'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(123528540968715125)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(123484501637715061)
,p_button_name=>'CANCEL'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_image_alt=>'Cancel'
,p_button_position=>'CLOSE'
,p_button_redirect_url=>'f?p=&APP_ID.:1:&SESSION.::&DEBUG.:::'
,p_button_condition_type=>'NEVER'
,p_grid_new_row=>'N'
,p_grid_new_column=>'N'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(123528670517715125)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_api.id(123484501637715061)
,p_button_name=>'MULTI_ROW_DELETE'
,p_button_action=>'REDIRECT_URL'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(47630389996858357)
,p_button_image_alt=>'Delete'
,p_button_position=>'DELETE'
,p_button_redirect_url=>'javascript:apex.confirm(htmldb_delete_message,''MULTI_ROW_DELETE'');'
,p_button_execute_validations=>'N'
,p_button_condition_type=>'NEVER'
,p_grid_new_row=>'N'
,p_grid_new_column=>'N'
);
wwv_flow_api.create_page_branch(
 p_id=>wwv_flow_api.id(123562923885715156)
,p_branch_action=>'f?p=&APP_ID.:5003:&SESSION.::&DEBUG.:::&success_msg=#SUCCESS_MSG#'
,p_branch_point=>'AFTER_PROCESSING'
,p_branch_type=>'REDIRECT_URL'
,p_branch_when_button_id=>wwv_flow_api.id(123528665166715125)
,p_branch_sequence=>1
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124177781511976946)
,p_name=>'P5003_DOCNUMBR'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_item_default=>'&P5000_TEST.'
,p_prompt=>'Docnumbr'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124211093341211419)
,p_name=>'P5003_COMPCODE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_COMPCODE.'
,p_prompt=>'Compcode'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124211414680211419)
,p_name=>'P5003_DOCTTYPE'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_DOCTTYPE.'
,p_prompt=>'Docttype'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124211810826211419)
,p_name=>'P5003_SUBTTYPE'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_SUBTTYPE.'
,p_prompt=>'Subttype'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124212171610211419)
,p_name=>'P5003_DOCTDATE'
,p_item_sequence=>50
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_DOCTDATE.'
,p_prompt=>'Doctdate'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124212628257211419)
,p_name=>'P5003_ITEMCODE'
,p_item_sequence=>60
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_ITEMCODE.'
,p_prompt=>'Itemcode'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124212972387211419)
,p_name=>'P5003_SERLNUMB'
,p_item_sequence=>70
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_SERLNUMB.'
,p_prompt=>'Serlnumb'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124376932618782602)
,p_name=>'P5003_PARTYCD1'
,p_item_sequence=>80
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_use_cache_before_default=>'NO'
,p_item_default=>'&P5000_PARTYCD1.'
,p_prompt=>'Partycd1'
,p_display_as=>'NATIVE_HIDDEN'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'N'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(124816451634156077)
,p_name=>'P5003_DOCDETAILS'
,p_item_sequence=>5
,p_item_plug_id=>wwv_flow_api.id(123484501637715061)
,p_prompt=>'Schedule Details'
,p_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select distinct DOCNUMBR||'' / ''||DOCTDATE from nmcusvlg',
'where DOCNUMBR=:P5000_DOCNUMBR'))
,p_source_type=>'QUERY'
,p_display_as=>'NATIVE_DISPLAY_ONLY'
,p_cSize=>30
,p_cMaxlength=>4000
,p_cHeight=>1
,p_cAttributes=>'nowrap'
,p_tag_attributes=>'style="color: blue;"'
,p_label_alignment=>'RIGHT'
,p_field_template=>wwv_flow_api.id(47629908389858329)
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_protection_level=>'S'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'Y'
,p_attribute_02=>'VALUE'
,p_attribute_04=>'Y'
,p_attribute_05=>'PLAIN'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(123686979871830140)
,p_name=>'add rows javascript'
,p_event_sequence=>10
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(123687427668830141)
,p_event_id=>wwv_flow_api.id(123686979871830140)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var $mydiv = $("#f14_0011");',
'    if ($mydiv.length){',
'/*alert(''test'');*/',
'}',
'else',
'{',
'for (i = 0; i <=5; i++)',
'{',
'javascript:addRow();',
'};',
'};',
'/*document.getElementById(''ITEMDESC'').readOnly = true;*/',
''))
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(124852464138399892)
,p_name=>'disable'
,p_event_sequence=>20
,p_triggering_element_type=>'JQUERY_SELECTOR'
,p_triggering_element=>'input[name="f34"]'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(124852790684399908)
,p_event_id=>wwv_flow_api.id(124852464138399892)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>wwv_flow_string.join(wwv_flow_t_varchar2(
'var el = this.triggeringElement.id;',
'var row = el.split("_")[1];',
'',
'if ($v(el) != '''') {',
'// disable the field',
'$x_disableItem("f30_" + row, true);',
'$x_disableItem("f31_" + row, true);',
'$x_disableItem("f28_" + row, true);',
'}',
'else {',
'// enable the field',
'$x_disableItem("f30_" + row, false);',
'$x_disableItem("f31_" + row, true);',
'$x_disableItem("f28_" + row, true);',
'}'))
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(123543135468715140)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_api.id(123484501637715061)
,p_process_type=>'NATIVE_TABFORM_UPDATE'
,p_process_name=>'ApplyMRU'
,p_attribute_02=>'NM_MRK_SCH_FOLLOWUP'
,p_attribute_03=>'ROWID'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_api.id(123528665166715125)
,p_process_success_message=>'#MRU_COUNT# row(s) updated, #MRI_COUNT# row(s) inserted.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(123543550719715144)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_api.id(123484501637715061)
,p_process_type=>'NATIVE_TABFORM_DELETE'
,p_process_name=>'ApplyMRD'
,p_attribute_02=>'NM_MRK_SCH_FOLLOWUP'
,p_attribute_03=>'ROWID'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'MULTI_ROW_DELETE'
,p_process_when_type=>'REQUEST_EQUALS_CONDITION'
,p_process_success_message=>'#MRD_COUNT# row(s) deleted.'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(124378457726864916)
,p_process_sequence=>30
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_region_id=>wwv_flow_api.id(123484501637715061)
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Pre_Insert'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'begin',
':COMPCODE:=:P5003_COMPCODE;',
':DOCNUMBR:=:P5003_DOCNUMBR;',
':DOCTTYPE:=:P5003_DOCTTYPE;',
':SUBTTYPE:=:P5003_SUBTTYPE;',
':DOCTDATE:=:P5003_DOCTDATE;',
':PARTYCDE:=:P5003_PARTYCD1;',
':SERLNUMB:=:P5003_SERLNUMB;	',
':ITEMCODE:=:P5003_ITEMCODE;	',
':OPRSTAMP:=:APP_USER;',
':TIMSTAMP:=sysdate;		',
'end;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_api.id(123528665166715125)
,p_exec_cond_for_each_row=>'Y'
);
wwv_flow_api.component_end;
end;
/
