prompt --application/pages/page_00052
begin
--   Manifest
--     PAGE: 00052
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>999901
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>52
,p_user_interface_id=>wwv_flow_api.id(1120121017230736040)
,p_name=>'SRVCSTYP'
,p_page_mode=>'MODAL'
,p_step_title=>'SRVCSTYP'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'ADMIN'
,p_last_upd_yyyymmddhh24miss=>'20200514225633'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(43809940720915235)
,p_plug_name=>'SRVCSTYP'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(1582248360698857849)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select COMPCODE,',
'       SRVTYPNM,',
'       SERLNUMB,',
'       REMARKSS,',
'       OPRSTAMP,',
'       TIMSTAMP,',
'       SVCTYPPK,',
'       MODIFYDT,',
'       GROUPCDE,',
'       CLIMFLAG',
'  from SRVCSTYP'))
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>8.5
,p_prn_height=>11
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#9bafde'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'normal'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#efefef'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(43651292137725847)
,p_max_row_count=>'1000000'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'ADMIN'
,p_internal_uid=>43651292137725847
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43651383217725848)
,p_db_column_name=>'COMPCODE'
,p_display_order=>10
,p_column_identifier=>'A'
,p_column_label=>'Compcode'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43651483459725849)
,p_db_column_name=>'SRVTYPNM'
,p_display_order=>20
,p_column_identifier=>'B'
,p_column_label=>'Srvtypnm'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43651518675725850)
,p_db_column_name=>'SERLNUMB'
,p_display_order=>30
,p_column_identifier=>'C'
,p_column_label=>'Serlnumb'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43855712648948501)
,p_db_column_name=>'REMARKSS'
,p_display_order=>40
,p_column_identifier=>'D'
,p_column_label=>'Remarkss'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43855843795948502)
,p_db_column_name=>'OPRSTAMP'
,p_display_order=>50
,p_column_identifier=>'E'
,p_column_label=>'Oprstamp'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43855914814948503)
,p_db_column_name=>'TIMSTAMP'
,p_display_order=>60
,p_column_identifier=>'F'
,p_column_label=>'Timstamp'
,p_column_type=>'DATE'
,p_column_alignment=>'CENTER'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43856078499948504)
,p_db_column_name=>'SVCTYPPK'
,p_display_order=>70
,p_column_identifier=>'G'
,p_column_label=>'Svctyppk'
,p_column_link=>'f?p=&APP_ID.:53:&SESSION.::&DEBUG.:RP,53:P53_SVCTYPPK:#SVCTYPPK#'
,p_column_linktext=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil.png" class="apex-edit-pencil" alt="">'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43856172086948505)
,p_db_column_name=>'MODIFYDT'
,p_display_order=>80
,p_column_identifier=>'H'
,p_column_label=>'Modifydt'
,p_column_type=>'DATE'
,p_column_alignment=>'CENTER'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43856287333948506)
,p_db_column_name=>'GROUPCDE'
,p_display_order=>90
,p_column_identifier=>'I'
,p_column_label=>'Groupcde'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(43856317606948507)
,p_db_column_name=>'CLIMFLAG'
,p_display_order=>100
,p_column_identifier=>'J'
,p_column_label=>'Climflag'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(43867786361949790)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'438678'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'COMPCODE:SRVTYPNM:SERLNUMB:REMARKSS:OPRSTAMP:TIMSTAMP:SVCTYPPK:MODIFYDT:GROUPCDE:CLIMFLAG'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(43818157516915387)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(43809940720915235)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--iconRight'
,p_button_template_id=>wwv_flow_api.id(1582272254158857926)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Create'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:53:&SESSION.::&DEBUG.:53'
);
wwv_flow_api.create_page_computation(
 p_id=>wwv_flow_api.id(43819579238915389)
,p_computation_sequence=>1
,p_computation_item=>'P53_SVCTYPPK'
,p_computation_type=>'STATIC_ASSIGNMENT'
,p_compute_when=>'CREATE'
,p_compute_when_type=>'REQUEST_EQUALS_CONDITION'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(43819875462915389)
,p_name=>'Edit Report - Dialog Closed'
,p_event_sequence=>10
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_api.id(43809940720915235)
,p_bind_type=>'bind'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(43820328014915389)
,p_event_id=>wwv_flow_api.id(43819875462915389)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(43809940720915235)
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(43818544810915387)
,p_name=>'Create Button - Dialog Closed'
,p_event_sequence=>20
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(43818157516915387)
,p_bind_type=>'bind'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(43819011234915387)
,p_event_id=>wwv_flow_api.id(43818544810915387)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(43809940720915235)
);
wwv_flow_api.component_end;
end;
/
