prompt --application/pages/page_00242
begin
--   Manifest
--     PAGE: 00242
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>100100
,p_default_application_id=>999901
,p_default_id_offset=>0
,p_default_owner=>'ORBRGS'
);
wwv_flow_api.create_page(
 p_id=>242
,p_user_interface_id=>wwv_flow_api.id(1120121017230736040)
,p_name=>'Service Charge Master'
,p_page_mode=>'MODAL'
,p_step_title=>'Service Charge Master'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_autocomplete_on_off=>'ON'
,p_step_template=>wwv_flow_api.id(1582223062813857794)
,p_page_template_options=>'#DEFAULT#'
,p_help_text=>'No help is available for this page.'
,p_last_updated_by=>'RILADM'
,p_last_upd_yyyymmddhh24miss=>'20200505114329'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(208528980687964524)
,p_plug_name=>'Service Charge Master'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(1582248360698857849)
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'Select ROWID rwid,SRVCNOPK, COMPCODE, RATEDATE, TIMSTAMP, ',
'ACTIVFLG, SRVCCODE, SRVCNAME, SRVMASCD, VHLMASCD, ',
'GRPMASCD, SJOBRATE, SREQTIME, RAISEDBY, APPRVDBY, ',
'APPRDATE, REMARKSS, LBORCHRG, ',
'SREQDAYS, MODELCDE, MODCRGAM, MODDISAM, ',
'CRGPRCNT, MODIFYDT, LABORGRP, COMMGRUP from nmcrgmas'))
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(208529061424964524)
,p_name=>'Service Charge Master'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'RILADM'
,p_internal_uid=>208529061424964524
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7114406109109939)
,p_db_column_name=>'RWID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Rwid'
,p_allow_sorting=>'N'
,p_allow_filtering=>'N'
,p_allow_highlighting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'OTHER'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_rpt_show_filter_lov=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7114863610109940)
,p_db_column_name=>'SRVCNOPK'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Srvcnopk'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7115205878109940)
,p_db_column_name=>'COMPCODE'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Compcode'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7115601591109942)
,p_db_column_name=>'RATEDATE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Ratedate'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7116095237109942)
,p_db_column_name=>'TIMSTAMP'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Timstamp'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7116472559109942)
,p_db_column_name=>'ACTIVFLG'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Activ Flg'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7116804835109942)
,p_db_column_name=>'SRVCCODE'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Service Code'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7117237957109942)
,p_db_column_name=>'SRVCNAME'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Service Name'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7117613236109942)
,p_db_column_name=>'SRVMASCD'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Service System'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7118090880109943)
,p_db_column_name=>'VHLMASCD'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Vhlmascd'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7118419136109943)
,p_db_column_name=>'GRPMASCD'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Grpmascd'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7118840947109943)
,p_db_column_name=>'SJOBRATE'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Sjobrate'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7119245144109945)
,p_db_column_name=>'SREQTIME'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Sreqtime'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7119616939109945)
,p_db_column_name=>'RAISEDBY'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Raisedby'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7120051635109945)
,p_db_column_name=>'APPRVDBY'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Apprvdby'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7120418178109945)
,p_db_column_name=>'APPRDATE'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Apprdate'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7120835435109945)
,p_db_column_name=>'REMARKSS'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Remarks'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7121253127109945)
,p_db_column_name=>'LBORCHRG'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Lborchrg'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7121629136109945)
,p_db_column_name=>'SREQDAYS'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Sreqdays'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7122074807109945)
,p_db_column_name=>'MODELCDE'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Modelcde'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7122423098109945)
,p_db_column_name=>'MODCRGAM'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Modcrgam'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7122823507109946)
,p_db_column_name=>'MODDISAM'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Moddisam'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7123207148109946)
,p_db_column_name=>'CRGPRCNT'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Crgprcnt'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7123653916109946)
,p_db_column_name=>'MODIFYDT'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Modifydt'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7124077101109946)
,p_db_column_name=>'LABORGRP'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Laborgrp'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(7124463025109946)
,p_db_column_name=>'COMMGRUP'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Commgrup'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(208576444584993002)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'71248'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'SRVCCODE:SRVCNAME:SRVMASCD:REMARKSS:ACTIVFLG:'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(7125236374109950)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_api.id(208528980687964524)
,p_button_name=>'SERVICE_CHARGE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(1582272837479857929)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Add Service Charge'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_button_redirect_url=>'f?p=&APP_ID.:245:&SESSION.::&DEBUG.:245::'
,p_button_condition_type=>'NEVER'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(7125689741109950)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_api.id(208528980687964524)
,p_button_name=>'CANCEL'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(1582272837479857929)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Cancel'
,p_button_position=>'RIGHT_OF_IR_SEARCH_BAR'
,p_warn_on_unsaved_changes=>null
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(7126083133109951)
,p_name=>'cancel dialog'
,p_event_sequence=>10
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(7125689741109950)
,p_bind_type=>'bind'
,p_bind_event_type=>'click'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(7126574973109951)
,p_event_id=>wwv_flow_api.id(7126083133109951)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_DIALOG_CANCEL'
);
wwv_flow_api.component_end;
end;
/
